/*
 * Copyright 2021 Ian Jones. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package com.eqixiac.equinix.design.optimizer;

import com.eqixiac.equinix.Fabric;
import com.eqixiac.equinix.core.WireMockTestBase;
import com.eqixiac.equinix.core.enums.MetroCode;
import com.eqixiac.equinix.core.model.MetroId;
import com.eqixiac.equinix.design.optimizer.model.DeploymentTopology;
import com.eqixiac.equinix.design.optimizer.model.MetroRecommendation;
import com.eqixiac.equinix.design.optimizer.model.MetroScore;
import com.eqixiac.equinix.design.optimizer.model.OptimizationRequest;
import com.eqixiac.equinix.design.optimizer.model.OptimizationResult;
import com.eqixiac.equinix.design.optimizer.model.ProviderAvailability;
import com.eqixiac.equinix.design.optimizer.model.ProviderRequirement;
import com.eqixiac.equinix.design.optimizer.model.WorkloadPlacement;
import com.eqixiac.equinix.design.optimizer.model.WorkloadSpec;
import com.eqixiac.equinix.design.optimizer.wizard.enums.BackboneTopology;
import com.eqixiac.equinix.design.optimizer.wizard.enums.BandwidthStrategy;
import com.eqixiac.equinix.design.optimizer.wizard.enums.ConnectionPurpose;
import com.eqixiac.equinix.design.optimizer.wizard.model.DeploymentOutcome;
import com.eqixiac.equinix.design.optimizer.wizard.model.DeploymentPlan;
import com.eqixiac.equinix.design.optimizer.wizard.model.ExecutionInputs;
import com.eqixiac.equinix.design.optimizer.wizard.model.PlannedCloudRouter;
import com.eqixiac.equinix.design.optimizer.wizard.model.PlannedConnection;
import com.eqixiac.equinix.design.optimizer.wizard.model.ProvisionedResource;
import com.eqixiac.equinix.design.optimizer.wizard.model.ProvisioningError;
import com.eqixiac.equinix.design.value.ratecard.PriceQuote;
import com.eqixiac.equinix.design.value.ratecard.PriceSource;
import com.eqixiac.equinix.design.value.ratecard.RateCard;
import com.eqixiac.equinix.fabric.enums.ConnectionType;
import com.eqixiac.equinix.fabric.enums.GatewayPackageCode;
import com.eqixiac.equinix.fabric.model.implementation.cloud.CloudProviderType;
import org.junit.jupiter.api.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Currency;
import java.util.List;
import java.util.Optional;

import static com.eqixiac.equinix.core.ResponseStubs.*;
import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Drives the wizard's provisioning surface — {@link DeploymentPlan#execute()},
 * {@link DeploymentPlan#dryRun()}, and {@link DeploymentPlan#rollback(DeploymentOutcome)} — against a
 * WireMock-backed {@link Fabric}. The plan itself is generated by the real engine (via
 * {@code fabric.deploymentWizard(result).plan()}); the Fabric create/get/delete endpoints are stubbed so
 * the poll-until-PROVISIONED waiter resolves on the first fetch and the ordering / UUID capture can be
 * asserted end to end.
 *
 * <p>Before this suite, {@code execute()} / {@code dryRun()} / {@code rollback()} had no coverage — every
 * wizard test built a {@code DeploymentPlan} POJO by hand and never exercised the Fabric calls.</p>
 */
class DeploymentPlanExecutionWireMockTest extends WireMockTestBase {

    private static final String ROUTER_UUID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";
    private static final String CONNECTION_UUID = "3a58dd05-f46d-4b1d-a154-2e85c396ea85";
    private static final String RP_UUID = "f1e2d3c4-b5a6-7890-abcd-1234567890ef";

    static Fabric fabric;

    // Named MetroId constants, for readability. The topology lookup
    // (DeploymentTopology.forMetro) matches on VALUE, not reference identity — MetroId is a value
    // type that never interns, and against live data the recommendation's id and the placement's id
    // are always separate objects. Sharing an instance is therefore a convenience here, never a
    // requirement: do not propagate "these must be the same object" into new fixtures.
    private static final MetroId DC = MetroId.of(MetroCode.DC);
    private static final MetroId DA = MetroId.of(MetroCode.DA);

    @BeforeAll
    static void setUp() {
        fabric = new Fabric(testCredentials());
        redirectToWireMock(fabric);
        fabric.authenticate();
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (fabric != null) fabric.close();
    }

    @BeforeEach
    void resetBeforeEach() {
        resetStubs();
    }

    // ── execute() ──

    @Test
    @DisplayName("execute() provisions routers, connections, backbone and routing protocols and returns their UUIDs")
    void executeProvisionsInOrder() {
        stubCreatedResources();
        DeploymentPlan plan = twoMetroPlan();
        // plan()'s own layered validation issues Layer-2 router dry-runs + catalog GETs; clear the
        // journal so the verifies below count execute()'s wire traffic alone.
        wireMock.resetRequests();

        DeploymentOutcome outcome = plan.execute(awsInputs());

        assertTrue(outcome.isFullySuccessful(),
                () -> "expected a clean execution, got errors: " + outcome.getErrors());
        assertTrue(outcome.getErrors().isEmpty());

        // 2 Cloud Routers + 1 provider connection + 1 backbone link + 4 routing protocols = 8.
        List<ProvisionedResource> resources = outcome.getResources();
        assertEquals(8, resources.size());

        assertEquals(2, count(resources, "CloudRouter"));
        assertEquals(1, count(resources, "Connection"));
        assertEquals(1, count(resources, "BackboneLink"));
        assertEquals(4, count(resources, "RoutingProtocol"));

        // Routers come first, then the provider connection, then the backbone, then routing protocols.
        assertEquals("CloudRouter", resources.get(0).getResourceType());
        assertEquals("CloudRouter", resources.get(1).getResourceType());
        assertEquals("Connection", resources.get(2).getResourceType());
        assertEquals("BackboneLink", resources.get(3).getResourceType());
        assertEquals("RoutingProtocol", resources.get(4).getResourceType());

        // Provisioned resources carry the created UUIDs and the resolved PROVISIONED state.
        ProvisionedResource router = resources.get(0);
        assertEquals(ROUTER_UUID, router.getUuid());
        assertEquals("PROVISIONED", router.getStatus());
        assertEquals(CONNECTION_UUID, resources.get(2).getUuid());
        assertEquals(RP_UUID, resources.stream()
                .filter(r -> r.getResourceType().equals("RoutingProtocol")).findFirst().orElseThrow().getUuid());

        // The wire: two router POSTs. Each of the two connections (provider + backbone) is pre-flighted
        // with a live dry-run and only then created for real — so two dryRun=true POSTs and two real
        // POSTs. Then four routing-protocol POSTs.
        wireMock.verify(2, postRequestedFor(urlPathEqualTo("/fabric/v4/routers")));
        wireMock.verify(2, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true")));
        wireMock.verify(2, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", absent()));
        wireMock.verify(4, postRequestedFor(
                urlPathEqualTo("/fabric/v4/connections/" + CONNECTION_UUID + "/routingProtocols")));
    }

    @Test
    @DisplayName("execute() pre-flights the connection with the REAL A-side FCR uuid + the customer auth key, then creates it with the same complete body")
    void executeSendsPlannedFields() {
        stubCreatedResources();

        DeploymentPlan plan = twoMetroPlan();
        // Count only execute()'s wire traffic (plan() also dry-runs the routers over REST).
        wireMock.resetRequests();

        plan.execute(awsInputs());

        wireMock.verify(postRequestedFor(urlPathEqualTo("/fabric/v4/routers"))
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC")))
                .withRequestBody(matchingJsonPath("$.location.metroCode", equalTo("DC")))
                .withRequestBody(matchingJsonPath("$.package.code", equalTo("STANDARD"))));

        // The Layer-3a pre-flight: the connection dry-run (dryRun=true) carries the COMPLETE cloud VC
        // body — the real A-side FCR uuid (which only exists after Phase 1), and a Z-side cloud provider
        // access point with the customer's AWS Account ID authentication key, the seller region, the
        // service-profile uuid and the DOT1Q VLAN. This is exactly the body the old name+bandwidth shell
        // was missing (EQ-3142501 "Null value for aSide access point").
        wireMock.verify(postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true"))
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC-to-aws")))
                .withRequestBody(matchingJsonPath("$.bandwidth", equalTo("5000")))
                .withRequestBody(matchingJsonPath("$.aSide.accessPoint.type", equalTo("CLOUD_ROUTER")))
                .withRequestBody(matchingJsonPath("$.aSide.accessPoint.router.uuid", equalTo(ROUTER_UUID)))
                .withRequestBody(matchingJsonPath("$.zSide.accessPoint.authenticationKey", equalTo("123456789012")))
                .withRequestBody(matchingJsonPath("$.zSide.accessPoint.sellerRegion", equalTo("us-east-1")))
                .withRequestBody(matchingJsonPath("$.zSide.accessPoint.profile.uuid", equalTo("sp-aws")))
                .withRequestBody(matchingJsonPath("$.zSide.accessPoint.linkProtocol.vlanTag", equalTo("1001"))));

        // Only AFTER the dry-run passes is the connection created for real, with the same complete body.
        wireMock.verify(postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", absent())
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC-to-aws")))
                .withRequestBody(matchingJsonPath("$.aSide.accessPoint.router.uuid", equalTo(ROUTER_UUID)))
                .withRequestBody(matchingJsonPath("$.zSide.accessPoint.authenticationKey", equalTo("123456789012"))));
    }

    @Test
    @DisplayName("execute() aborts and rolls back everything already provisioned when a connection's pre-flight dry-run is rejected")
    void executeDryRunFailureAbortsAndRollsBack() {
        // Routers provision cleanly; the provider connection's live pre-flight dry-run is rejected. The
        // connection must NOT be created for real, and the two Cloud Routers already built must be
        // unwound (LIFO) rather than left billing against a plan that cannot complete.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/[^/]+", "/json/fabric/cloud_router_response.json");
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/routers/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));
        // Any POST to /connections (the pre-flight dry-run) is rejected.
        stubErrorInline(wireMock, "/fabric/v4/connections",
                422, "[{\"errorCode\":\"ERR-422\",\"errorMessage\":\"Bandwidth unavailable\"}]");

        DeploymentPlan plan = twoMetroPlan();
        wireMock.resetRequests();

        DeploymentOutcome outcome = plan.execute(awsInputs());

        assertFalse(outcome.isFullySuccessful());
        // The rejection is recorded as a pre-flight dry-run failure naming the connection.
        assertTrue(outcome.getErrors().stream()
                        .anyMatch(e -> e.getResourceType().equals("Connection")
                                && e.getResourceName().equals("FCR-DC-to-aws")
                                && e.getReason().contains("pre-flight dry-run rejected")),
                () -> "expected a pre-flight dry-run rejection, got: " + outcome.getErrors());

        // The connection was NEVER created for real — only the single failing dryRun=true POST was sent.
        wireMock.verify(1, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true")));
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", absent()));
        // The run aborted before Phase 4, so no routing protocols were attempted.
        wireMock.verify(0, postRequestedFor(urlPathMatching("/fabric/v4/connections/[^/]+/routingProtocols")));

        // The unwind: both Cloud Routers built in Phase 1 were rolled back — deleted, not left billing.
        wireMock.verify(2, deleteRequestedFor(urlPathMatching("/fabric/v4/routers/" + ROUTER_UUID)));
    }

    @Test
    @DisplayName("execute() does NOT abort on an INFEASIBLE (403) pre-flight: it records a skip and proceeds to the real create")
    void executePreflight403SkipsAndProceedsToRealCreate() {
        // Routers provision cleanly.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/[^/]+", "/json/fabric/cloud_router_response.json");
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/routers/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));
        // The pre-flight dry-run (dryRun=true) is answered 403 — the credential is not entitled to the
        // dry-run endpoint. That is an INFEASIBILITY, not a rejection: the run must NOT abort.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true"))
                .willReturn(aResponse().withStatus(403).withHeader("Content-Type", "application/json")
                        .withBody("[{\"errorCode\":\"ERR-403\",\"errorMessage\":\"Not entitled to dry-run\"}]")));
        // The REAL create (dryRun absent) succeeds — this is where any true error would surface.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", absent())
                .willReturn(created("/json/fabric/connection_provisioned_response.json")));
        stubSingleton(wireMock, "/fabric/v4/connections/[^/]+",
                "/json/fabric/connection_provisioned_response.json");
        wireMock.stubFor(post(urlPathMatching("/fabric/v4/connections/[^/]+/routingProtocols"))
                .willReturn(created("/json/fabric/routing_protocol_response.json")));

        DeploymentPlan plan = twoMetroPlan();
        wireMock.resetRequests();

        DeploymentOutcome outcome = plan.execute(awsInputs());

        // The provider connection was still created for real — the 403 pre-flight did NOT abort the run.
        assertTrue(outcome.getResources().stream()
                        .anyMatch(r -> r.getResourceType().equals("Connection")
                                && r.getName().equals("FCR-DC-to-aws")),
                () -> "the connection must be created despite the infeasible pre-flight: " + outcome.getResources());
        // Nothing was rolled back — the two Cloud Routers survive.
        assertEquals(2, count(outcome.getResources(), "CloudRouter"));
        wireMock.verify(0, deleteRequestedFor(urlPathMatching("/fabric/v4/routers/.*")));
        // A recoverable skip warning was recorded, naming the connection and the 403 infeasibility —
        // NOT a "pre-flight dry-run rejected" abort.
        ProvisioningError skip = outcome.getErrors().stream()
                .filter(e -> e.getResourceName().equals("FCR-DC-to-aws"))
                .findFirst().orElseThrow(() -> new AssertionError(
                        "expected a recorded pre-flight skip for the connection: " + outcome.getErrors()));
        assertTrue(skip.isRecoverable(), "an infeasible pre-flight skip is recoverable");
        assertTrue(skip.getReason().contains("pre-flight dry-run skipped") && skip.getReason().contains("403"),
                () -> "expected a skip reason naming the 403 infeasibility: " + skip.getReason());
        assertFalse(skip.getReason().contains("rejected"),
                () -> "an infeasibility must not be reported as a rejection: " + skip.getReason());

        // The connection was pre-flighted once (403) then created for real once.
        wireMock.verify(1, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true"))
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC-to-aws"))));
        wireMock.verify(1, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", absent())
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC-to-aws"))));
    }

    @Test
    @DisplayName("execute() DOES abort and roll back on a REJECTION (400) pre-flight — a well-formed request the API rejects is a real defect")
    void executePreflight400AbortsAndRollsBack() {
        // Routers provision cleanly; the provider connection's pre-flight dry-run is rejected 400 (a
        // validation rejection of a well-formed request). Unlike a 403 infeasibility, a rejection MUST
        // abort and unwind the two Cloud Routers rather than proceed to a doomed create.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/[^/]+", "/json/fabric/cloud_router_response.json");
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/routers/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));
        stubErrorInline(wireMock, "/fabric/v4/connections",
                400, "[{\"errorCode\":\"ERR-400\",\"errorMessage\":\"Invalid connection body\"}]");

        DeploymentPlan plan = twoMetroPlan();
        wireMock.resetRequests();

        DeploymentOutcome outcome = plan.execute(awsInputs());

        assertFalse(outcome.isFullySuccessful());
        assertTrue(outcome.getErrors().stream()
                        .anyMatch(e -> e.getResourceType().equals("Connection")
                                && e.getResourceName().equals("FCR-DC-to-aws")
                                && e.getReason().contains("pre-flight dry-run rejected")),
                () -> "a 400 rejection must be recorded as a pre-flight rejection: " + outcome.getErrors());
        // Never created for real — only the single failing dryRun=true POST was sent.
        wireMock.verify(1, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true")));
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", absent()));
        // Both Cloud Routers were rolled back (deleted), not left billing behind a plan that cannot complete.
        wireMock.verify(2, deleteRequestedFor(urlPathMatching("/fabric/v4/routers/" + ROUTER_UUID)));
    }

    @Test
    @DisplayName("execute() cannot throw IllegalArgumentException for package codes: a lenient 'standard' plan provisions cleanly, sending STANDARD")
    void executeLenientlyResolvedPackageCode() {
        // Regression: execute() used to do GatewayPackageCode.valueOf(planned.getPackageCode()) at
        // deploy time, so a plan built with routerPackage("standard") passed plan() and pricing but
        // blew up with IllegalArgumentException mid-deployment. The code is now resolved and
        // validated once at plan time; execute() consumes the enum.
        stubCreatedResources();

        DeploymentPlan plan = twoMetroPlan("standard");
        // Count only execute()'s two real router creates (plan() also dry-runs each router).
        wireMock.resetRequests();

        DeploymentOutcome outcome = plan.execute(awsInputs());

        assertTrue(outcome.isFullySuccessful(),
                () -> "a leniently-set package code must not fail at execute time, got: " + outcome.getErrors());
        wireMock.verify(2, postRequestedFor(urlPathEqualTo("/fabric/v4/routers"))
                .withRequestBody(matchingJsonPath("$.package.code", equalTo("STANDARD"))));
    }

    @Test
    @DisplayName("execute() never sends UNKNOWN: a hand-built plan with an UNKNOWN package records an error and issues no router POST")
    void executeRejectsUnknownPackageWithoutApiCall() {
        stubCreatedResources();

        DeploymentPlan plan = DeploymentPlan.builder()
                .cloudRouters(List.of(PlannedCloudRouter.builder()
                        .metroId(DC).name("FCR-DC")
                        .packageCode(GatewayPackageCode.UNKNOWN)
                        .build()))
                .providerConnections(List.of())
                .backboneLinks(List.of())
                .routingProtocols(List.of())
                .valid(true)
                .validationErrors(List.of())
                .fabric(fabric)
                .build();

        DeploymentOutcome outcome = plan.execute();

        assertFalse(outcome.isFullySuccessful());
        assertEquals(1, outcome.getErrors().size());
        ProvisioningError error = outcome.getErrors().get(0);
        assertEquals("CloudRouter", error.getResourceType());
        assertFalse(error.isRecoverable());
        assertTrue(error.getReason().contains("package code"), error.getReason());
        assertTrue(outcome.getResources().isEmpty(), "nothing must be provisioned");
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/routers")));
    }

    // ── execute() customer inputs + lens-3b pre-existing endpoints ──

    @Test
    @DisplayName("execute() fails fast and provisions NOTHING when a provider connection is missing its cloud authorization key")
    void executeMissingAuthKeyFailsFast() {
        stubCreatedResources();

        // twoMetroPlan has an AWS provider connection; the no-arg execute() supplies no key.
        DeploymentPlan plan = twoMetroPlan();
        wireMock.resetRequests();

        DeploymentOutcome outcome = plan.execute();

        assertFalse(outcome.isFullySuccessful());
        assertTrue(outcome.getResources().isEmpty(), "nothing must be provisioned before the fail-fast");
        // The error is non-recoverable and names the connection and the exact key to gather.
        ProvisioningError error = outcome.getErrors().stream()
                .filter(e -> e.getResourceName().equals("FCR-DC-to-aws"))
                .findFirst().orElseThrow();
        assertFalse(error.isRecoverable());
        assertTrue(error.getReason().contains("AWS Account ID"), error.getReason());
        // Not a single API call was issued — not even the routers.
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/routers")));
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/connections")));
    }

    @Test
    @DisplayName("execute() dry-runs and creates a lens-3b connection against a caller-supplied EXISTING FCR, using the key carried on the plan — no ExecutionInputs needed")
    void executeDryRunsAgainstPlanCarriedExistingEndpoint() {
        String existingFcr = "existing-fcr-uuid-1234";
        stubCreatedResources();

        // A provider connection whose A-side is an already-existing FCR (lens 3b), with its cloud
        // authorization key carried on the plan itself — so execute() needs no ExecutionInputs and
        // creates no Cloud Router.
        PlannedConnection conn = PlannedConnection.builder()
                .name("to-aws-existing")
                .connectionType(ConnectionType.IP_VC)
                .purpose(ConnectionPurpose.PROVIDER)
                .bandwidthMbps(1000)
                .aSideRouterName("no-phase1-router")
                .aSideExistingRouterUuid(existingFcr)
                .zSideServiceProfileUuid("sp-aws")
                .zSideProviderLabel("AWS")
                .zSideSellerRegion("us-east-1")
                .zSideCloudType(CloudProviderType.AWS)
                .zSideAuthenticationKey("123456789012")
                .zSideVlanTag(1100)
                .build();

        DeploymentPlan plan = DeploymentPlan.builder()
                .cloudRouters(List.of())
                .providerConnections(List.of(conn))
                .backboneLinks(List.of())
                .routingProtocols(List.of())
                .valid(true)
                .validationErrors(List.of())
                .fabric(fabric)
                .build();

        DeploymentOutcome outcome = plan.execute();

        assertTrue(outcome.isFullySuccessful(),
                () -> "lens-3b execution should succeed, got: " + outcome.getErrors());
        // No Cloud Router was created — the A-side already exists.
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/routers")));
        // The connection was pre-flighted, then created, both against the EXISTING FCR uuid.
        wireMock.verify(1, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true"))
                .withRequestBody(matchingJsonPath("$.aSide.accessPoint.router.uuid", equalTo(existingFcr)))
                .withRequestBody(matchingJsonPath("$.zSide.accessPoint.authenticationKey", equalTo("123456789012"))));
        wireMock.verify(1, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", absent())
                .withRequestBody(matchingJsonPath("$.aSide.accessPoint.router.uuid", equalTo(existingFcr))));
    }

    // ── execute() state waiter (awaitState poll loop) ──

    @Test
    @DisplayName("execute() polls a PROVISIONING router until a later fetch reports PROVISIONED")
    void executeWaiterPollsThroughStateTransition() {
        // Create returns a router still PROVISIONING; the FIRST get-by-uuid also reports
        // PROVISIONING, and only the SECOND reports PROVISIONED — so the waiter must actually
        // loop (one 5s poll interval) instead of resolving on the first fetch like every other
        // test in this suite.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_provisioning_response.json")));

        String scenario = "router-provisioning";
        wireMock.stubFor(get(urlPathMatching("/fabric/v4/routers/[^/]+"))
                .inScenario(scenario)
                .whenScenarioStateIs(com.github.tomakehurst.wiremock.stubbing.Scenario.STARTED)
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_provisioning_response.json")))
                .willSetStateTo("ready"));
        wireMock.stubFor(get(urlPathMatching("/fabric/v4/routers/[^/]+"))
                .inScenario(scenario)
                .whenScenarioStateIs("ready")
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));

        DeploymentOutcome outcome = singleRouterPlan().execute();

        assertTrue(outcome.isFullySuccessful(),
                () -> "the waiter should resolve once the second poll reports PROVISIONED: " + outcome.getErrors());
        ProvisionedResource router = outcome.getResources().get(0);
        assertEquals("PROVISIONED", router.getStatus(),
                "the recorded status is the state the waiter finally observed");
        // At least two polls: the PROVISIONING fetch and the PROVISIONED one.
        wireMock.verify(2, getRequestedFor(urlPathEqualTo("/fabric/v4/routers/" + ROUTER_UUID)));
    }

    @Test
    @DisplayName("execute() records the REAL terminal state when the waiter hits a terminal failure")
    void executeWaiterRecordsTerminalFailure() {
        // The router create succeeds but every poll reports NOT_PROVISIONED — one of the waiter's
        // terminal failure states — so awaitState() gives up immediately (no 5-minute wait) and
        // execute() records a recoverable error naming the REAL terminal state (not a mislabelled
        // "PROVISIONING") while keeping the resource so rollback can find it.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_provisioning_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/[^/]+",
                "/json/fabric/cloud_router_not_provisioned_response.json");

        DeploymentOutcome outcome = singleRouterPlan().execute();

        assertFalse(outcome.isFullySuccessful());
        ProvisioningError error = outcome.getErrors().stream()
                .filter(e -> e.getResourceType().equals("CloudRouter"))
                .findFirst().orElseThrow();
        assertTrue(error.isRecoverable(), "a state-waiter failure is retryable");
        assertTrue(error.getReason().contains("reached terminal state NOT_PROVISIONED"),
                "the error reports the actual terminal state observed: " + error.getReason());

        // The resource is still recorded — with the REAL observed state — so rollback can find it.
        ProvisionedResource router = outcome.getResources().get(0);
        assertEquals(ROUTER_UUID, router.getUuid());
        assertEquals("NOT_PROVISIONED", router.getStatus(),
                "a terminally-failed wait records the state that actually held, never PROVISIONING");

        // failWhen fires on the very first fetch: exactly one poll, no timeout burn.
        wireMock.verify(1, getRequestedFor(urlPathEqualTo("/fabric/v4/routers/" + ROUTER_UUID)));
    }

    @Test
    @DisplayName("a connection that lands FAILED stops polling immediately, reports FAILED, and its routing protocols are skipped")
    void executeConnectionTerminalFailureSkipsRoutingProtocols() {
        // Router provisions cleanly; the provider connection's create succeeds but the first poll
        // reports FAILED — a state that will never become PROVISIONED. The old code passed Set.of()
        // as the terminal set here, so it polled the full 5-minute timeout, misreported the
        // connection as "PROVISIONING", and Phase 4 still attempted routing protocols on it.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/[^/]+", "/json/fabric/cloud_router_response.json");
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/connections"))
                .willReturn(created("/json/fabric/connection_provisioned_response.json")));
        wireMock.stubFor(get(urlPathMatching("/fabric/v4/connections/[^/]+"))
                .willReturn(okJson("{\"uuid\": \"" + CONNECTION_UUID + "\", \"state\": \"FAILED\"}")));
        wireMock.stubFor(post(urlPathMatching("/fabric/v4/connections/[^/]+/routingProtocols"))
                .willReturn(created("/json/fabric/routing_protocol_response.json")));

        PlannedConnection conn = PlannedConnection.builder()
                .name("to-aws-failing")
                .connectionType(ConnectionType.IP_VC)
                .purpose(ConnectionPurpose.PROVIDER)
                .bandwidthMbps(1000)
                .aSideRouterName("FCR-DC")
                .zSideServiceProfileUuid("sp-aws")
                .zSideProviderLabel("AWS")
                .zSideSellerRegion("us-east-1")
                .zSideCloudType(CloudProviderType.AWS)
                .zSideAuthenticationKey("123456789012")
                .zSideVlanTag(1001)
                .build();
        DeploymentPlan plan = DeploymentPlan.builder()
                .cloudRouters(List.of(PlannedCloudRouter.builder()
                        .metroId(DC).name("FCR-DC").packageCode(GatewayPackageCode.STANDARD)
                        .build()))
                .providerConnections(List.of(conn))
                .backboneLinks(List.of())
                .routingProtocols(List.of(
                        com.eqixiac.equinix.design.optimizer.wizard.model.PlannedRoutingProtocol.builder()
                                .name("to-aws-failing-DIR")
                                .connectionName("to-aws-failing")
                                .type(com.eqixiac.equinix.fabric.enums.RoutingProtocolType.DIRECT)
                                .equinixIfaceIpv4("10.100.0.1/30")
                                .build(),
                        com.eqixiac.equinix.design.optimizer.wizard.model.PlannedRoutingProtocol.builder()
                                .name("to-aws-failing-BGP")
                                .connectionName("to-aws-failing")
                                .type(com.eqixiac.equinix.fabric.enums.RoutingProtocolType.BGP)
                                .customerAsn(65100L)
                                .customerPeerIpv4("10.100.0.2/30").equinixPeerIpv4("10.100.0.1/30")
                                .build()))
                .valid(true)
                .validationErrors(List.of())
                .fabric(fabric)
                .build();
        wireMock.resetRequests();

        DeploymentOutcome outcome = plan.execute();

        assertFalse(outcome.isFullySuccessful());
        // The connection error names the REAL terminal state and says the protocols are skipped.
        ProvisioningError connError = outcome.getErrors().stream()
                .filter(e -> e.getResourceType().equals("Connection")
                        && e.getResourceName().equals("to-aws-failing"))
                .findFirst().orElseThrow(() -> new AssertionError(
                        "expected a terminal-state connection error: " + outcome.getErrors()));
        assertTrue(connError.getReason().contains("reached terminal state FAILED"),
                "the real terminal state, never 'PROVISIONING': " + connError.getReason());
        assertTrue(connError.getReason().contains("routing protocols skipped"), connError.getReason());

        // The recorded resource carries the REAL state.
        ProvisionedResource resource = outcome.getResources().stream()
                .filter(r -> r.getResourceType().equals("Connection"))
                .findFirst().orElseThrow();
        assertEquals("FAILED", resource.getStatus());

        // Both dependent routing protocols were skipped — no POST was ever attempted for them.
        assertEquals(2, outcome.getErrors().stream()
                        .filter(e -> e.getResourceType().equals("RoutingProtocol")
                                && e.getReason().contains("was not provisioned"))
                        .count(),
                () -> "both protocols must be skipped as unprovisionable: " + outcome.getErrors());
        wireMock.verify(0, postRequestedFor(urlPathMatching("/fabric/v4/connections/[^/]+/routingProtocols")));

        // failWhen fires on the very first poll — no 5-minute timeout burn.
        wireMock.verify(1, getRequestedFor(urlPathEqualTo("/fabric/v4/connections/" + CONNECTION_UUID)));
    }

    // ── execute() refuses an invalid plan (billable-resource guard) ──

    @Test
    @DisplayName("execute() throws IllegalStateException listing the validation errors when the plan is invalid — nothing is provisioned")
    void executeRefusesInvalidPlan() {
        stubCreatedResources();

        DeploymentPlan invalid = DeploymentPlan.builder()
                .cloudRouters(List.of(PlannedCloudRouter.builder()
                        .metroId(DC).name("FCR-DC").packageCode(GatewayPackageCode.STANDARD)
                        .build()))
                .providerConnections(List.of())
                .backboneLinks(List.of())
                .routingProtocols(List.of())
                .valid(false)
                .validationErrors(List.of(
                        "Cloud Router 'FCR-DC' (DC) has no notification email: Fabric requires at "
                                + "least one notification recipient to create a Cloud Router."))
                .fabric(fabric)
                .build();
        wireMock.resetRequests();

        IllegalStateException ex = assertThrows(IllegalStateException.class, invalid::execute);
        assertTrue(ex.getMessage().contains("re-plan"),
                "the message tells the caller to fix and re-plan: " + ex.getMessage());
        assertTrue(ex.getMessage().contains("no notification email"),
                "the message lists the recorded validation errors: " + ex.getMessage());

        // Nothing was provisioned — not a single API call.
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/routers")));
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/connections")));
    }

    // ── router-body parity: plan-time dry-run vs execute-time create (shared RouterBodies) ──

    @Test
    @DisplayName("the plan-time router dry-run and the execute-time real create send IDENTICAL wire bodies (both from RouterBodies)")
    void routerDryRunAndCreateSendIdenticalBodies() throws Exception {
        // The defect this pins: execute() Phase 1 used to hand-assemble its own router body WITHOUT
        // the Fabric-mandated notifications (EQ-3040013) and with unguarded null account/project
        // refs, while the Layer-2 dry-run (PlanValidator) stamped them — so a green dry-run was
        // followed by every real create 400ing. Both paths now flow through RouterBodies; this test
        // captures both requests off the wire and diffs them.
        stubCreatedResources();
        DeploymentPlan plan = twoMetroPlan(); // plan() dry-runs both routers over REST
        plan.execute(awsInputs());            // Phase 1 creates both routers for real

        List<com.github.tomakehurst.wiremock.verification.LoggedRequest> dryRuns =
                wireMock.findAll(postRequestedFor(urlPathEqualTo("/fabric/v4/routers"))
                        .withQueryParam("dryRun", equalTo("true")));
        List<com.github.tomakehurst.wiremock.verification.LoggedRequest> creates =
                wireMock.findAll(postRequestedFor(urlPathEqualTo("/fabric/v4/routers"))
                        .withQueryParam("dryRun", absent()));
        assertEquals(2, dryRuns.size(), "one dry-run per planned router (FCR-DC, FCR-DA)");
        assertEquals(2, creates.size(), "one real create per planned router");

        com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
        java.util.Map<String, com.fasterxml.jackson.databind.JsonNode> dryByName = new java.util.HashMap<>();
        for (var req : dryRuns) {
            com.fasterxml.jackson.databind.JsonNode body = mapper.readTree(req.getBodyAsString());
            dryByName.put(body.get("name").asText(), body);
        }
        for (var req : creates) {
            com.fasterxml.jackson.databind.JsonNode body = mapper.readTree(req.getBodyAsString());
            String name = body.get("name").asText();
            assertEquals(dryByName.get(name), body,
                    "the real create body for '" + name + "' must equal the dry-run body it was "
                            + "validated as — same notifications, same null guards");
            // And the notification regression in particular: the REAL create carries the mandatory
            // notifications (EQ-3040013), which the old hand-assembled body dropped.
            assertEquals("noc@example.com", body.at("/notifications/0/emails/0").asText(),
                    "the real create stamps the mandatory notification recipient: " + body);
            // The null account/project guard: no null-valued account/project refs are sent.
            assertTrue(body.path("account").isMissingNode() || !body.path("account").isNull(),
                    "no AccountRef(null) is fabricated for an unset account: " + body);
        }
    }

    /** A hand-built single-router plan so waiter tests poll exactly one resource. */
    private DeploymentPlan singleRouterPlan() {
        return DeploymentPlan.builder()
                .cloudRouters(List.of(PlannedCloudRouter.builder()
                        .metroId(DC).name("FCR-DC")
                        .packageCode(GatewayPackageCode.STANDARD)
                        .build()))
                .providerConnections(List.of())
                .backboneLinks(List.of())
                .routingProtocols(List.of())
                .valid(true)
                .validationErrors(List.of())
                .fabric(fabric)
                .build();
    }

    // ── dryRun() ──

    @Test
    @DisplayName("dryRun() DEFERS a keyless provider connection's live endpoint dry-run (never posts a connection) and enumerates its required inputs")
    void dryRunDefersKeylessConnection() {
        // The provider connection has no pre-existing endpoint and no authorization key, so its live
        // endpoint dry-run cannot run at plan time: dryRun() must DEFER it (never POST a doomed
        // endpoint-less connection) and enumerate the AWS Account ID the customer must gather. The
        // Layer-2 router dry-run still runs for real.
        stubRouterDryRunOk();
        DeploymentPlan plan = twoMetroPlan();
        wireMock.resetRequests();

        DeploymentPlan validated = plan.dryRun();

        // No connection is posted at plan time — the endpoint-less dry-run that fails with EQ-3142501
        // is never sent; it is deferred to provisioning instead.
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/connections")));

        assertNotNull(validated.getDeferredValidations());
        assertTrue(validated.getDeferredValidations().stream().anyMatch(d -> d.contains("FCR-DC-to-aws")),
                () -> "connection should be deferred, got: " + validated.getDeferredValidations());
        assertNotNull(validated.getRequiredInputs());
        assertTrue(validated.getRequiredInputs().stream()
                        .anyMatch(r -> r.getConnectionName().equals("FCR-DC-to-aws")
                                && r.getCloudType() == CloudProviderType.AWS
                                && r.isAuthenticationKeyRequired()),
                () -> "AWS key should be enumerated as a required input, got: " + validated.getRequiredInputs());
    }

    @Test
    @DisplayName("dryRun() surfaces a live router dry-run rejection as a plan validation error")
    void dryRunSurfacesRouterRejection() {
        // The Layer-2 router dry-run (POST /routers?dryRun=true) is rejected → dryRun() folds it into
        // the validation errors and reports the plan invalid.
        stubErrorInline(wireMock, "/fabric/v4/routers",
                400, "[{\"errorCode\":\"ERR-400\",\"errorMessage\":\"Invalid router spec\"}]");

        DeploymentPlan validated = twoMetroPlan().dryRun();

        assertFalse(validated.isValid());
        assertFalse(validated.getValidationErrors().isEmpty());
        assertTrue(validated.getValidationErrors().stream().anyMatch(e -> e.contains("FCR-D")),
                () -> "expected a router dry-run rejection naming the router, got: "
                        + validated.getValidationErrors());
    }

    // ── rollback() ──

    @Test
    @DisplayName("rollback() deletes connections and routers in reverse order and returns no failures on success")
    void rollbackDeletesProvisionedResources() {
        stubCreatedResources();
        // Deletes read the deleted resource from the body, so return a body (not 204).
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/connections/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/connection_provisioned_response.json"))));
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/routers/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));

        DeploymentPlan plan = twoMetroPlan();
        DeploymentOutcome outcome = plan.execute(awsInputs());
        assertTrue(outcome.isFullySuccessful());

        List<ProvisioningError> failures = plan.rollback(outcome);

        assertTrue(failures.isEmpty(), () -> "clean rollback expected, got: " + failures);

        // The provider connection and the backbone link are both deleted (2 connection DELETEs), and both
        // Cloud Routers are deleted (2 router DELETEs). Routing protocols are torn down with their parent.
        wireMock.verify(2, deleteRequestedFor(urlPathMatching("/fabric/v4/connections/" + CONNECTION_UUID)));
        wireMock.verify(2, deleteRequestedFor(urlPathMatching("/fabric/v4/routers/" + ROUTER_UUID)));
    }

    @Test
    @DisplayName("rollback() records a delete failure as a non-recoverable error rather than throwing")
    void rollbackCapturesDeleteFailure() {
        stubCreatedResources();
        stubErrorInline(wireMock, "/fabric/v4/connections/.*",
                500, "[{\"errorCode\":\"ERR-500\",\"errorMessage\":\"Delete failed\"}]");
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/routers/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));

        DeploymentPlan plan = twoMetroPlan();
        DeploymentOutcome outcome = plan.execute(awsInputs());

        List<ProvisioningError> failures = plan.rollback(outcome);

        assertFalse(failures.isEmpty(), "the connection delete failures should be captured");
        assertTrue(failures.stream().allMatch(f -> !f.isRecoverable()));
        assertTrue(failures.stream().anyMatch(f -> f.getReason().contains("rollback delete failed")));
    }

    @Test
    @DisplayName("rollback() of a null outcome is a no-op returning no failures")
    void rollbackNullOutcome() {
        DeploymentPlan plan = twoMetroPlan();
        assertTrue(plan.rollback(null).isEmpty());
    }

    // ── stubbing helpers ──

    /** Stubs the create + get-by-uuid endpoints so execute()'s waiter resolves PROVISIONED immediately. */
    private static void stubCreatedResources() {
        // Cloud Router: create + get (fixture state is PROVISIONED).
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/[^/]+", "/json/fabric/cloud_router_response.json");

        // Connection: create + get (fixture state is PROVISIONED).
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/connections"))
                .willReturn(created("/json/fabric/connection_provisioned_response.json")));
        stubSingleton(wireMock, "/fabric/v4/connections/[^/]+",
                "/json/fabric/connection_provisioned_response.json");

        // Routing protocols: POST /connections/{id}/routingProtocols.
        wireMock.stubFor(post(urlPathMatching("/fabric/v4/connections/[^/]+/routingProtocols"))
                .willReturn(created("/json/fabric/routing_protocol_response.json")));
    }

    private static com.github.tomakehurst.wiremock.client.ResponseDefinitionBuilder created(String fixture) {
        return aResponse().withStatus(201)
                .withHeader("Content-Type", "application/json")
                .withBody(loadFixture(fixture));
    }

    /** Stubs the Layer-2 plan-time router dry-run (POST /routers?dryRun=true) to succeed. */
    private static void stubRouterDryRunOk() {
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
    }

    /** Stubs the sp-aws service-profile lookup so plan()'s Layer-1 catalog checks resolve and pass. */
    private static void stubServiceProfileOk() {
        wireMock.stubFor(get(urlPathMatching("/fabric/v4/serviceProfiles/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/service_profile_response.json"))));
    }

    /**
     * The per-connection authorization a first-time customer supplies at execution: the AWS Account ID
     * and DOT1Q VLAN for the {@code FCR-DC-to-aws} provider connection of {@link #twoMetroPlan()}.
     */
    private static ExecutionInputs awsInputs() {
        return ExecutionInputs.builder()
                .authenticationKey("FCR-DC-to-aws", "123456789012")
                .vlanTag("FCR-DC-to-aws", 1001)
                .build();
    }

    private static long count(List<ProvisionedResource> resources, String type) {
        return resources.stream().filter(r -> r.getResourceType().equals(type)).count();
    }

    private static RateCard heuristicRateCard() {
        // A rate card that always returns a quote, so pricing never touches fabric.prices() over the wire.
        return new RateCard() {
            @Override
            public Optional<PriceQuote> connection(ConnectionType type, int bandwidthMbps, MetroCode metro,
                                                   com.eqixiac.equinix.design.value.ratecard.Term term) {
                return Optional.of(PriceQuote.of(BigDecimal.valueOf(500), BigDecimal.ZERO,
                        Currency.getInstance("USD"), PriceSource.ESTIMATE));
            }

            @Override
            public Optional<PriceQuote> cloudRouter(String packageCode, MetroCode metro,
                                                    com.eqixiac.equinix.design.value.ratecard.Term term) {
                return Optional.of(PriceQuote.of(BigDecimal.valueOf(300), BigDecimal.ZERO,
                        Currency.getInstance("USD"), PriceSource.ESTIMATE));
            }

            @Override
            public PriceSource source() {
                return PriceSource.ESTIMATE;
            }
        };
    }

    /**
     * A two-metro plan generated by the real engine: DC (AWS provider, one 5000 Mbps AWS-dependent
     * workload) and DA (no provider). Full-mesh backbone → one DC-DA link. Pricing is pinned to a
     * heuristic rate card so no pricing HTTP is issued.
     */
    private DeploymentPlan twoMetroPlan() {
        return twoMetroPlan("STANDARD");
    }

    private DeploymentPlan twoMetroPlan(String routerPackage) {
        MetroScore score = new MetroScore(90.0, java.util.Collections.emptyList());

        WorkloadSpec ml = WorkloadSpec.builder()
                .label("ML Training").bandwidthMbps(5000)
                .dependsOnProviders(List.of(ProviderRequirement.builder().label("AWS").build()))
                .build();

        OptimizationResult result = OptimizationResult.builder()
                .request(OptimizationRequest.builder().workloads(List.of(ml)).build())
                .recommendations(List.of(
                        MetroRecommendation.builder()
                                .rank(1).metroId(DC).metroName("Ashburn").score(score).reasons(List.of("Primary"))
                                .availableProviders(List.of(
                                        ProviderAvailability.builder()
                                                .providerLabel("AWS")
                                                .available(true)
                                                .sellerRegions(List.of("us-east-1"))
                                                .serviceProfileUuid("sp-aws")
                                                .build()))
                                .build(),
                        MetroRecommendation.builder()
                                .rank(2).metroId(DA).metroName("Dallas").score(score).reasons(List.of("Secondary"))
                                .availableProviders(java.util.Collections.emptyList())
                                .build()))
                .topology(new DeploymentTopology(List.of(
                        WorkloadPlacement.builder()
                                .workloadLabel("ML Training")
                                .assignedMetro(DC)
                                .reasoning("AWS at DC")
                                .build())))
                .computedAt(Instant.now())
                .computeTimeMs(10)
                .build();

        // plan() now runs Layer-1 catalog checks whose failure would (rightly) invalidate the plan —
        // and execute() refuses an invalid plan — so the sp-aws service-profile lookup must resolve.
        stubServiceProfileOk();

        return fabric.deploymentWizard(result)
                .routerPackage(routerPackage)
                .routerNamePrefix("FCR")
                // IP_VC (the new default, set explicitly here): every planned connection has a Cloud
                // Router A-side, which Fabric accepts only as IP_VC (FCR A-side => IP_VC fix).
                .providerConnectionType(ConnectionType.IP_VC)
                .backboneConnectionType(ConnectionType.IP_VC)
                .backboneBandwidthMbps(10_000)
                .backboneTopology(BackboneTopology.FULL_MESH)
                .bandwidthStrategy(BandwidthStrategy.PER_WORKLOAD)
                .customerAsn(65100L)
                .withBFD(true, 300)
                .notifications("noc@example.com")
                .rateCard(heuristicRateCard())
                .plan();
    }
}
