/*
 * Copyright 2021 Ian Jones. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package api.equinix.javasdk.design.optimizer;

import api.equinix.javasdk.Fabric;
import api.equinix.javasdk.core.WireMockTestBase;
import api.equinix.javasdk.core.enums.MetroCode;
import api.equinix.javasdk.core.model.MetroId;
import api.equinix.javasdk.design.optimizer.model.DeploymentTopology;
import api.equinix.javasdk.design.optimizer.model.MetroRecommendation;
import api.equinix.javasdk.design.optimizer.model.MetroScore;
import api.equinix.javasdk.design.optimizer.model.OptimizationRequest;
import api.equinix.javasdk.design.optimizer.model.OptimizationResult;
import api.equinix.javasdk.design.optimizer.model.ProviderAvailability;
import api.equinix.javasdk.design.optimizer.model.ProviderRequirement;
import api.equinix.javasdk.design.optimizer.model.WorkloadPlacement;
import api.equinix.javasdk.design.optimizer.model.WorkloadSpec;
import api.equinix.javasdk.design.optimizer.wizard.enums.BackboneTopology;
import api.equinix.javasdk.design.optimizer.wizard.enums.BandwidthStrategy;
import api.equinix.javasdk.design.optimizer.wizard.model.DeploymentOutcome;
import api.equinix.javasdk.design.optimizer.wizard.model.DeploymentPlan;
import api.equinix.javasdk.design.optimizer.wizard.model.ProvisionedResource;
import api.equinix.javasdk.design.optimizer.wizard.model.ProvisioningError;
import api.equinix.javasdk.design.value.ratecard.PriceQuote;
import api.equinix.javasdk.design.value.ratecard.PriceSource;
import api.equinix.javasdk.design.value.ratecard.RateCard;
import api.equinix.javasdk.fabric.enums.ConnectionType;
import org.junit.jupiter.api.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Currency;
import java.util.List;
import java.util.Optional;

import static api.equinix.javasdk.core.ResponseStubs.*;
import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Drives the wizard's provisioning surface — {@link DeploymentPlan#execute()},
 * {@link DeploymentPlan#dryRun()}, and {@link DeploymentPlan#rollback(DeploymentOutcome)} — against a
 * WireMock-backed {@link Fabric}. The plan itself is generated by the real engine (via
 * {@code fabric.deploymentWizard(result).plan()}); the Fabric create/get/delete endpoints are stubbed so
 * the poll-until-PROVISIONED waiter resolves on the first fetch and the ordering / UUID capture can be
 * asserted end to end.
 *
 * <p>Before this suite, {@code execute()} / {@code dryRun()} / {@code rollback()} had no coverage — every
 * wizard test built a {@code DeploymentPlan} POJO by hand and never exercised the Fabric calls.</p>
 */
class DeploymentPlanExecutionWireMockTest extends WireMockTestBase {

    private static final String ROUTER_UUID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";
    private static final String CONNECTION_UUID = "3a58dd05-f46d-4b1d-a154-2e85c396ea85";
    private static final String RP_UUID = "f1e2d3c4-b5a6-7890-abcd-1234567890ef";

    static Fabric fabric;

    // Shared MetroId instances so the engine's reference-based topology lookup resolves.
    private static final MetroId DC = MetroId.of(MetroCode.DC);
    private static final MetroId DA = MetroId.of(MetroCode.DA);

    @BeforeAll
    static void setUp() {
        fabric = new Fabric(testCredentials());
        redirectToWireMock(fabric);
        fabric.authenticate();
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (fabric != null) fabric.close();
    }

    @BeforeEach
    void resetBeforeEach() {
        resetStubs();
    }

    // ── execute() ──

    @Test
    @DisplayName("execute() provisions routers, connections, backbone and routing protocols and returns their UUIDs")
    void executeProvisionsInOrder() {
        stubCreatedResources();
        DeploymentPlan plan = twoMetroPlan();

        DeploymentOutcome outcome = plan.execute();

        assertTrue(outcome.isFullySuccessful(),
                () -> "expected a clean execution, got errors: " + outcome.getErrors());
        assertTrue(outcome.getErrors().isEmpty());

        // 2 Cloud Routers + 1 provider connection + 1 backbone link + 4 routing protocols = 8.
        List<ProvisionedResource> resources = outcome.getResources();
        assertEquals(8, resources.size());

        assertEquals(2, count(resources, "CloudRouter"));
        assertEquals(1, count(resources, "Connection"));
        assertEquals(1, count(resources, "BackboneLink"));
        assertEquals(4, count(resources, "RoutingProtocol"));

        // Routers come first, then the provider connection, then the backbone, then routing protocols.
        assertEquals("CloudRouter", resources.get(0).getResourceType());
        assertEquals("CloudRouter", resources.get(1).getResourceType());
        assertEquals("Connection", resources.get(2).getResourceType());
        assertEquals("BackboneLink", resources.get(3).getResourceType());
        assertEquals("RoutingProtocol", resources.get(4).getResourceType());

        // Provisioned resources carry the created UUIDs and the resolved PROVISIONED state.
        ProvisionedResource router = resources.get(0);
        assertEquals(ROUTER_UUID, router.getUuid());
        assertEquals("PROVISIONED", router.getStatus());
        assertEquals(CONNECTION_UUID, resources.get(2).getUuid());
        assertEquals(RP_UUID, resources.stream()
                .filter(r -> r.getResourceType().equals("RoutingProtocol")).findFirst().orElseThrow().getUuid());

        // The wire: two router POSTs, two connection POSTs (provider + backbone), four routing-protocol POSTs.
        wireMock.verify(2, postRequestedFor(urlPathEqualTo("/fabric/v4/routers")));
        wireMock.verify(2, postRequestedFor(urlPathEqualTo("/fabric/v4/connections")));
        wireMock.verify(4, postRequestedFor(
                urlPathEqualTo("/fabric/v4/connections/" + CONNECTION_UUID + "/routingProtocols")));
    }

    @Test
    @DisplayName("execute() posts the planned router name/metro/package and the connection name/bandwidth")
    void executeSendsPlannedFields() {
        stubCreatedResources();

        twoMetroPlan().execute();

        wireMock.verify(postRequestedFor(urlPathEqualTo("/fabric/v4/routers"))
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC")))
                .withRequestBody(matchingJsonPath("$.location.metroCode", equalTo("DC")))
                .withRequestBody(matchingJsonPath("$.package.code", equalTo("STANDARD"))));

        // Provider connection: FCR-DC-to-aws sized to the single 5000 Mbps AWS-dependent workload.
        wireMock.verify(postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC-to-aws")))
                .withRequestBody(matchingJsonPath("$.bandwidth", equalTo("5000"))));
    }

    @Test
    @DisplayName("execute() captures a create failure as a recoverable error without aborting the rest of the plan")
    void executeCapturesConnectionFailure() {
        // Routers succeed; the connection POST fails. execute() must record the error but keep going,
        // and the routing protocols whose parent connection never provisioned become their own errors.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/.*", "/json/fabric/cloud_router_response.json");
        stubErrorInline(wireMock, "/fabric/v4/connections",
                422, "[{\"errorCode\":\"ERR-422\",\"errorMessage\":\"Bandwidth unavailable\"}]");

        DeploymentOutcome outcome = twoMetroPlan().execute();

        assertFalse(outcome.isFullySuccessful());
        // The 2 routers still provisioned.
        assertEquals(2, count(outcome.getResources(), "CloudRouter"));
        // Both connection POSTs (provider + backbone) failed → 2 connection errors, plus the 4 routing
        // protocols orphaned by the missing parent connections.
        assertTrue(outcome.getErrors().stream()
                .anyMatch(e -> e.getResourceType().equals("Connection")));
        assertTrue(outcome.getErrors().stream()
                .anyMatch(e -> e.getResourceType().equals("RoutingProtocol")
                        && e.getReason().contains("was not provisioned")
                        && !e.isRecoverable()));
    }

    // ── dryRun() ──

    @Test
    @DisplayName("dryRun() validates each provider connection via the dryRun create and reports the plan valid")
    void dryRunValidatesConnections() {
        // dryRun create hits POST /connections?dryRun=true; return a connection body for it.
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/connections"))
                .willReturn(okJson(loadFixture("/json/fabric/connection_provisioned_response.json"))));

        DeploymentPlan validated = twoMetroPlan().dryRun();

        assertTrue(validated.isValid(),
                () -> "dry run should pass, errors: " + validated.getValidationErrors());
        assertTrue(validated.getValidationErrors().isEmpty());

        // Only provider connections are dry-run validated (one here); every request carries dryRun=true and
        // creates nothing durably. Cloud Routers and backbone links are NOT dry-run created.
        wireMock.verify(1, postRequestedFor(urlPathEqualTo("/fabric/v4/connections"))
                .withQueryParam("dryRun", equalTo("true"))
                .withRequestBody(matchingJsonPath("$.name", equalTo("FCR-DC-to-aws"))));
        wireMock.verify(0, postRequestedFor(urlPathEqualTo("/fabric/v4/routers")));
    }

    @Test
    @DisplayName("dryRun() surfaces a validation failure from the dryRun create as a plan validation error")
    void dryRunSurfacesValidationError() {
        stubErrorInline(wireMock, "/fabric/v4/connections",
                400, "[{\"errorCode\":\"ERR-400\",\"errorMessage\":\"Invalid connection spec\"}]");

        DeploymentPlan validated = twoMetroPlan().dryRun();

        assertFalse(validated.isValid());
        assertFalse(validated.getValidationErrors().isEmpty());
        assertTrue(validated.getValidationErrors().stream()
                .anyMatch(e -> e.contains("FCR-DC-to-aws")));
    }

    // ── rollback() ──

    @Test
    @DisplayName("rollback() deletes connections and routers in reverse order and returns no failures on success")
    void rollbackDeletesProvisionedResources() {
        stubCreatedResources();
        // Deletes read the deleted resource from the body, so return a body (not 204).
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/connections/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/connection_provisioned_response.json"))));
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/routers/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));

        DeploymentPlan plan = twoMetroPlan();
        DeploymentOutcome outcome = plan.execute();
        assertTrue(outcome.isFullySuccessful());

        List<ProvisioningError> failures = plan.rollback(outcome);

        assertTrue(failures.isEmpty(), () -> "clean rollback expected, got: " + failures);

        // The provider connection and the backbone link are both deleted (2 connection DELETEs), and both
        // Cloud Routers are deleted (2 router DELETEs). Routing protocols are torn down with their parent.
        wireMock.verify(2, deleteRequestedFor(urlPathMatching("/fabric/v4/connections/" + CONNECTION_UUID)));
        wireMock.verify(2, deleteRequestedFor(urlPathMatching("/fabric/v4/routers/" + ROUTER_UUID)));
    }

    @Test
    @DisplayName("rollback() records a delete failure as a non-recoverable error rather than throwing")
    void rollbackCapturesDeleteFailure() {
        stubCreatedResources();
        stubErrorInline(wireMock, "/fabric/v4/connections/.*",
                500, "[{\"errorCode\":\"ERR-500\",\"errorMessage\":\"Delete failed\"}]");
        wireMock.stubFor(delete(urlPathMatching("/fabric/v4/routers/.*"))
                .willReturn(okJson(loadFixture("/json/fabric/cloud_router_response.json"))));

        DeploymentPlan plan = twoMetroPlan();
        DeploymentOutcome outcome = plan.execute();

        List<ProvisioningError> failures = plan.rollback(outcome);

        assertFalse(failures.isEmpty(), "the connection delete failures should be captured");
        assertTrue(failures.stream().allMatch(f -> !f.isRecoverable()));
        assertTrue(failures.stream().anyMatch(f -> f.getReason().contains("rollback delete failed")));
    }

    @Test
    @DisplayName("rollback() of a null outcome is a no-op returning no failures")
    void rollbackNullOutcome() {
        DeploymentPlan plan = twoMetroPlan();
        assertTrue(plan.rollback(null).isEmpty());
    }

    // ── stubbing helpers ──

    /** Stubs the create + get-by-uuid endpoints so execute()'s waiter resolves PROVISIONED immediately. */
    private static void stubCreatedResources() {
        // Cloud Router: create + get (fixture state is PROVISIONED).
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/routers"))
                .willReturn(created("/json/fabric/cloud_router_response.json")));
        stubSingleton(wireMock, "/fabric/v4/routers/[^/]+", "/json/fabric/cloud_router_response.json");

        // Connection: create + get (fixture state is PROVISIONED).
        wireMock.stubFor(post(urlPathEqualTo("/fabric/v4/connections"))
                .willReturn(created("/json/fabric/connection_provisioned_response.json")));
        stubSingleton(wireMock, "/fabric/v4/connections/[^/]+",
                "/json/fabric/connection_provisioned_response.json");

        // Routing protocols: POST /connections/{id}/routingProtocols.
        wireMock.stubFor(post(urlPathMatching("/fabric/v4/connections/[^/]+/routingProtocols"))
                .willReturn(created("/json/fabric/routing_protocol_response.json")));
    }

    private static com.github.tomakehurst.wiremock.client.ResponseDefinitionBuilder created(String fixture) {
        return aResponse().withStatus(201)
                .withHeader("Content-Type", "application/json")
                .withBody(loadFixture(fixture));
    }

    private static long count(List<ProvisionedResource> resources, String type) {
        return resources.stream().filter(r -> r.getResourceType().equals(type)).count();
    }

    private static RateCard heuristicRateCard() {
        // A rate card that always returns a quote, so pricing never touches fabric.prices() over the wire.
        return new RateCard() {
            @Override
            public Optional<PriceQuote> connection(ConnectionType type, int bandwidthMbps, MetroCode metro,
                                                   api.equinix.javasdk.design.value.ratecard.Term term) {
                return Optional.of(PriceQuote.of(BigDecimal.valueOf(500), BigDecimal.ZERO,
                        Currency.getInstance("USD"), PriceSource.ESTIMATE));
            }

            @Override
            public Optional<PriceQuote> cloudRouter(String packageCode, MetroCode metro,
                                                    api.equinix.javasdk.design.value.ratecard.Term term) {
                return Optional.of(PriceQuote.of(BigDecimal.valueOf(300), BigDecimal.ZERO,
                        Currency.getInstance("USD"), PriceSource.ESTIMATE));
            }

            @Override
            public PriceSource source() {
                return PriceSource.ESTIMATE;
            }
        };
    }

    /**
     * A two-metro plan generated by the real engine: DC (AWS provider, one 5000 Mbps AWS-dependent
     * workload) and DA (no provider). Full-mesh backbone → one DC-DA link. Pricing is pinned to a
     * heuristic rate card so no pricing HTTP is issued.
     */
    private DeploymentPlan twoMetroPlan() {
        MetroScore score = new MetroScore(90.0, java.util.Collections.emptyList());

        WorkloadSpec ml = WorkloadSpec.builder()
                .label("ML Training").bandwidthMbps(5000)
                .dependsOnProviders(List.of(ProviderRequirement.builder().label("AWS").build()))
                .build();

        OptimizationResult result = OptimizationResult.builder()
                .request(OptimizationRequest.builder().workloads(List.of(ml)).build())
                .recommendations(List.of(
                        MetroRecommendation.builder()
                                .rank(1).metroId(DC).metroName("Ashburn").score(score).reasons(List.of("Primary"))
                                .availableProviders(List.of(
                                        new ProviderAvailability("AWS", true, List.of("us-east-1"), "sp-aws")))
                                .build(),
                        MetroRecommendation.builder()
                                .rank(2).metroId(DA).metroName("Dallas").score(score).reasons(List.of("Secondary"))
                                .availableProviders(java.util.Collections.emptyList())
                                .build()))
                .topology(new DeploymentTopology(List.of(
                        new WorkloadPlacement("ML Training", DC, "AWS at DC"))))
                .computedAt(Instant.now())
                .computeTimeMs(10)
                .build();

        return fabric.deploymentWizard(result)
                .routerPackage("STANDARD")
                .routerNamePrefix("FCR")
                .providerConnectionType(ConnectionType.EVPL_VC)
                .backboneConnectionType(ConnectionType.EVPL_VC)
                .backboneBandwidthMbps(10_000)
                .backboneTopology(BackboneTopology.FULL_MESH)
                .bandwidthStrategy(BandwidthStrategy.PER_WORKLOAD)
                .customerAsn(65100L)
                .withBFD(true, 300)
                .rateCard(heuristicRateCard())
                .plan();
    }
}
