package com.eqixiac.equinix.fabric.enums;

public enum ConnectionOperationType {
    CONNECTION_CREATION_ACCEPTANCE,
    CONNECTION_CREATION_REJECTION,
    CONNECTION_UPDATE_ACCEPTANCE,
    CONNECTION_UPDATE_REJECTION,
    CONNECTION_DELETION_ACCEPTANCE,
    CONNECTION_REJECTION_ACCEPTANCE,
    CONNECTION_UPDATE_REQUEST,
    MIGRATION_EVPL_VC,
    CONNECTION_PROVIDER_STATUS_REQUEST,
    CONNECTION_PROVIDER_BANDWIDTH_REQUEST,
    ACCEPT_HOSTED_CONNECTION,
    CANCEL_EVPL_VC_DRAFT_ORDERS,
    CONNECTION_CREATION_RETRY,
    CONNECTION_DELETION_RETRY
}
