package api.equinix.javasdk.fabric.enums;

public enum ConnectionOperationType {
    CONNECTION_CREATION_ACCEPTANCE,
    CONNECTION_CREATION_REJECTION,
    CONNECTION_UPDATE_ACCEPTANCE,
    CONNECTION_UPDATE_REJECTION,
    CONNECTION_DELETION_ACCEPTANCE,
    CONNECTION_PROVIDER_STATUS_REQUEST
}
