package api.equinix.javasdk.design.export;

import api.equinix.javasdk.fabric.enums.RoutingProtocolType;
import api.equinix.javasdk.design.optimizer.wizard.model.DeploymentPlan;
import api.equinix.javasdk.design.optimizer.wizard.model.PlannedBackboneLink;
import api.equinix.javasdk.design.optimizer.wizard.model.PlannedCloudRouter;
import api.equinix.javasdk.design.optimizer.wizard.model.PlannedConnection;
import api.equinix.javasdk.design.optimizer.wizard.model.PlannedRoutingProtocol;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders a {@link DeploymentPlan} produced by the Deployment Wizard into
 * Infrastructure-as-Code (HCL) for the
 * <a href="https://registry.terraform.io/providers/equinix/equinix/latest">Equinix Terraform provider</a>.
 *
 * <p>The exporter only emits the resource types the plan actually contains and keeps
 * attributes faithful to the fields the plan provides; it does not invent provider
 * attributes that cannot be sourced from the plan. The generated HCL is intended as a
 * readable, version-controllable starting point for {@code terraform plan} / {@code apply}.</p>
 *
 * <p>Resource mapping:</p>
 * <ul>
 *     <li>{@link PlannedCloudRouter} &rarr; {@code resource "equinix_fabric_cloud_router"}</li>
 *     <li>{@link PlannedConnection} (provider connections and backbone links)
 *         &rarr; {@code resource "equinix_fabric_connection"}</li>
 *     <li>{@link PlannedRoutingProtocol} &rarr; {@code resource "equinix_fabric_routing_protocol"}</li>
 * </ul>
 *
 * <p>This class is stateless and thread-safe; a single instance may be reused.</p>
 */
public class TerraformExporter {

    private static final String INDENT = "  ";

    /**
     * Exports the given deployment plan as Equinix Terraform provider HCL.
     *
     * @param plan the deployment plan to export; must not be {@code null}
     * @return a self-contained HCL document. Resources are emitted in dependency
     *         order (cloud routers, then connections, then routing protocols), and
     *         later resources reference earlier ones via Terraform resource expressions.
     * @throws IllegalArgumentException if {@code plan} is {@code null}
     */
    public String export(DeploymentPlan plan) {
        if (plan == null) {
            throw new IllegalArgumentException("plan must not be null");
        }

        StringBuilder hcl = new StringBuilder();
        writeHeader(hcl, plan);

        // Map of planned cloud-router name -> Terraform resource label, so connections
        // can reference the routers they sit on via interpolation.
        Map<String, String> routerLabels = new LinkedHashMap<>();
        // Map of planned connection name -> Terraform resource label, so routing
        // protocols can reference their parent connection.
        Map<String, String> connectionLabels = new LinkedHashMap<>();

        writeCloudRouters(hcl, plan, routerLabels);
        writeProviderConnections(hcl, plan, routerLabels, connectionLabels);
        writeBackboneLinks(hcl, plan, routerLabels, connectionLabels);
        writeRoutingProtocols(hcl, plan, connectionLabels);

        return hcl.toString();
    }

    private void writeHeader(StringBuilder hcl, DeploymentPlan plan) {
        hcl.append("# ----------------------------------------------------------------------------\n");
        hcl.append("# Equinix Fabric deployment - generated by the Equinix Java SDK\n");
        hcl.append("# Deployment Wizard (api.equinix.javasdk.design.export.TerraformExporter).\n");
        hcl.append("#\n");
        hcl.append("# ").append(plan.toSummary().replace("\n", "\n# ")).append("\n");
        hcl.append("#\n");
        hcl.append("# Review carefully before running `terraform apply`. Some provider attributes\n");
        hcl.append("# (e.g. credentials, account/project context) may need to be supplied via\n");
        hcl.append("# variables before this configuration is complete.\n");
        hcl.append("# ----------------------------------------------------------------------------\n\n");

        hcl.append("terraform {\n");
        hcl.append(INDENT).append("required_providers {\n");
        hcl.append(INDENT).append(INDENT).append("equinix = {\n");
        hcl.append(INDENT).append(INDENT).append(INDENT).append("source = \"equinix/equinix\"\n");
        hcl.append(INDENT).append(INDENT).append("}\n");
        hcl.append(INDENT).append("}\n");
        hcl.append("}\n\n");
    }

    private void writeCloudRouters(StringBuilder hcl, DeploymentPlan plan, Map<String, String> routerLabels) {
        List<PlannedCloudRouter> routers = plan.getCloudRouters();
        if (routers == null || routers.isEmpty()) {
            return;
        }

        hcl.append("# === Cloud Routers ===\n\n");
        for (PlannedCloudRouter cr : routers) {
            String label = uniqueLabel(routerLabels.values(), "fcr", cr.getName());
            routerLabels.put(cr.getName(), label);

            hcl.append("resource \"equinix_fabric_cloud_router\" \"").append(label).append("\" {\n");
            hcl.append(attr(1, "name", cr.getName()));
            hcl.append(attr(1, "type", "XF_ROUTER"));

            hcl.append(INDENT).append("package {\n");
            hcl.append(attr(2, "code", cr.getPackageCode()));
            hcl.append(INDENT).append("}\n");

            hcl.append(INDENT).append("location {\n");
            hcl.append(attr(2, "metro_code", String.valueOf(cr.getMetroCode())));
            hcl.append(INDENT).append("}\n");

            if (cr.getAccountNumber() != null) {
                hcl.append(INDENT).append("account {\n");
                hcl.append(rawAttr(2, "account_number", String.valueOf(cr.getAccountNumber())));
                hcl.append(INDENT).append("}\n");
            }

            if (cr.getProjectId() != null) {
                hcl.append(INDENT).append("project {\n");
                hcl.append(attr(2, "project_id", cr.getProjectId()));
                hcl.append(INDENT).append("}\n");
            }

            if (cr.getNotificationEmail() != null) {
                hcl.append(INDENT).append("notifications {\n");
                hcl.append(attr(2, "type", "ALL"));
                hcl.append(rawAttr(2, "emails", "[" + quote(cr.getNotificationEmail()) + "]"));
                hcl.append(INDENT).append("}\n");
            }

            hcl.append("}\n\n");
        }
    }

    private void writeProviderConnections(StringBuilder hcl, DeploymentPlan plan,
                                          Map<String, String> routerLabels,
                                          Map<String, String> connectionLabels) {
        List<PlannedConnection> connections = plan.getProviderConnections();
        if (connections == null || connections.isEmpty()) {
            return;
        }

        hcl.append("# === Provider Connections ===\n\n");
        for (PlannedConnection conn : connections) {
            String label = uniqueLabel(connectionLabels.values(), "conn", conn.getName());
            connectionLabels.put(conn.getName(), label);

            hcl.append("resource \"equinix_fabric_connection\" \"").append(label).append("\" {\n");
            hcl.append(attr(1, "name", conn.getName()));
            if (conn.getConnectionType() != null) {
                hcl.append(attr(1, "type", String.valueOf(conn.getConnectionType())));
            }
            hcl.append(rawAttr(1, "bandwidth", String.valueOf(conn.getBandwidthMbps())));

            if (conn.getNotificationEmail() != null) {
                hcl.append(INDENT).append("notifications {\n");
                hcl.append(attr(2, "type", "ALL"));
                hcl.append(rawAttr(2, "emails", "[" + quote(conn.getNotificationEmail()) + "]"));
                hcl.append(INDENT).append("}\n");
            }

            // A-side: the Cloud Router this connection originates from.
            writeASideRouter(hcl, conn.getASideRouterName(), routerLabels);

            // Z-side: a service-profile redemption (provider connection).
            hcl.append(INDENT).append("z_side {\n");
            hcl.append(INDENT).append(INDENT).append("access_point {\n");
            hcl.append(attr(3, "type", "SP"));
            if (conn.getZSideServiceProfileUuid() != null) {
                hcl.append(INDENT).append(INDENT).append(INDENT).append("profile {\n");
                hcl.append(attr(4, "type", "L2_PROFILE"));
                hcl.append(attr(4, "uuid", conn.getZSideServiceProfileUuid()));
                hcl.append(INDENT).append(INDENT).append(INDENT).append("}\n");
            }
            else if (conn.getZSideProviderLabel() != null) {
                hcl.append(comment(3, "Service profile UUID not resolved for provider: "
                        + conn.getZSideProviderLabel()));
            }
            if (conn.getZSideSellerRegion() != null) {
                hcl.append(attr(3, "seller_region", conn.getZSideSellerRegion()));
            }
            hcl.append(INDENT).append(INDENT).append("}\n");
            hcl.append(INDENT).append("}\n");

            hcl.append("}\n\n");
        }
    }

    private void writeBackboneLinks(StringBuilder hcl, DeploymentPlan plan,
                                    Map<String, String> routerLabels,
                                    Map<String, String> connectionLabels) {
        List<PlannedBackboneLink> links = plan.getBackboneLinks();
        if (links == null || links.isEmpty()) {
            return;
        }

        hcl.append("# === Backbone Links (Cloud Router to Cloud Router) ===\n\n");
        for (PlannedBackboneLink link : links) {
            PlannedConnection conn = link.getConnection();
            String connName = conn != null ? conn.getName() : link.getName();
            String label = uniqueLabel(connectionLabels.values(), "backbone", connName);
            connectionLabels.put(connName, label);

            hcl.append("resource \"equinix_fabric_connection\" \"").append(label).append("\" {\n");
            hcl.append(attr(1, "name", link.getName()));
            if (conn != null && conn.getConnectionType() != null) {
                hcl.append(attr(1, "type", String.valueOf(conn.getConnectionType())));
            }
            hcl.append(rawAttr(1, "bandwidth", String.valueOf(link.getBandwidthMbps())));

            // A-side router.
            String aRouterName = conn != null ? conn.getASideRouterName() : null;
            writeASideRouter(hcl, aRouterName, routerLabels);

            // Z-side router (the far end of the backbone link).
            String zRouterName = conn != null ? conn.getZSideRouterName() : null;
            hcl.append(INDENT).append("z_side {\n");
            hcl.append(INDENT).append(INDENT).append("access_point {\n");
            hcl.append(attr(3, "type", "CLOUD_ROUTER"));
            String zLabel = zRouterName != null ? routerLabels.get(zRouterName) : null;
            if (zLabel != null) {
                hcl.append(INDENT).append(INDENT).append(INDENT).append("router {\n");
                hcl.append(rawAttr(4, "uuid",
                        "equinix_fabric_cloud_router." + zLabel + ".id"));
                hcl.append(INDENT).append(INDENT).append(INDENT).append("}\n");
            }
            else if (zRouterName != null) {
                hcl.append(comment(3, "Z-side Cloud Router not found in plan: " + zRouterName));
            }
            hcl.append(INDENT).append(INDENT).append("}\n");
            hcl.append(INDENT).append("}\n");

            hcl.append("}\n\n");
        }
    }

    private void writeASideRouter(StringBuilder hcl, String routerName, Map<String, String> routerLabels) {
        hcl.append(INDENT).append("a_side {\n");
        hcl.append(INDENT).append(INDENT).append("access_point {\n");
        hcl.append(attr(3, "type", "CLOUD_ROUTER"));
        String label = routerName != null ? routerLabels.get(routerName) : null;
        if (label != null) {
            hcl.append(INDENT).append(INDENT).append(INDENT).append("router {\n");
            hcl.append(rawAttr(4, "uuid", "equinix_fabric_cloud_router." + label + ".id"));
            hcl.append(INDENT).append(INDENT).append(INDENT).append("}\n");
        }
        else if (routerName != null) {
            hcl.append(comment(3, "A-side Cloud Router not found in plan: " + routerName));
        }
        hcl.append(INDENT).append(INDENT).append("}\n");
        hcl.append(INDENT).append("}\n");
    }

    private void writeRoutingProtocols(StringBuilder hcl, DeploymentPlan plan,
                                       Map<String, String> connectionLabels) {
        List<PlannedRoutingProtocol> protocols = plan.getRoutingProtocols();
        if (protocols == null || protocols.isEmpty()) {
            return;
        }

        hcl.append("# === Routing Protocols ===\n\n");
        for (PlannedRoutingProtocol rp : protocols) {
            String label = uniqueLabel(new ArrayList<>(), "rp", rp.getName());

            hcl.append("resource \"equinix_fabric_routing_protocol\" \"").append(label).append("\" {\n");
            hcl.append(attr(1, "name", rp.getName()));
            if (rp.getType() != null) {
                hcl.append(attr(1, "type", String.valueOf(rp.getType())));
            }

            // Bind the protocol to its parent connection.
            String connLabel = connectionLabels.get(rp.getConnectionName());
            if (connLabel != null) {
                hcl.append(rawAttr(1, "connection_uuid",
                        "equinix_fabric_connection." + connLabel + ".id"));
            }
            else if (rp.getConnectionName() != null) {
                hcl.append(comment(1, "Parent connection not found in plan: " + rp.getConnectionName()));
            }

            if (rp.getType() == RoutingProtocolType.DIRECT) {
                writeDirectProtocol(hcl, rp);
            }
            else if (rp.getType() == RoutingProtocolType.BGP) {
                writeBgpProtocol(hcl, rp);
            }

            hcl.append("}\n\n");
        }
    }

    private void writeDirectProtocol(StringBuilder hcl, PlannedRoutingProtocol rp) {
        if (rp.getEquinixIfaceIpv4() != null) {
            hcl.append(INDENT).append("direct_ipv4 {\n");
            hcl.append(attr(2, "equinix_iface_ip", rp.getEquinixIfaceIpv4()));
            hcl.append(INDENT).append("}\n");
        }
    }

    private void writeBgpProtocol(StringBuilder hcl, PlannedRoutingProtocol rp) {
        if (rp.getCustomerAsn() != null) {
            hcl.append(rawAttr(1, "customer_asn", String.valueOf(rp.getCustomerAsn())));
        }
        if (rp.getCustomerPeerIpv4() != null || rp.getEquinixPeerIpv4() != null) {
            hcl.append(INDENT).append("bgp_ipv4 {\n");
            if (rp.getCustomerPeerIpv4() != null) {
                hcl.append(attr(2, "customer_peer_ip", rp.getCustomerPeerIpv4()));
            }
            if (rp.getEquinixPeerIpv4() != null) {
                hcl.append(attr(2, "equinix_peer_ip", rp.getEquinixPeerIpv4()));
            }
            hcl.append(rawAttr(2, "enabled", "true"));
            hcl.append(INDENT).append("}\n");
        }
        if (rp.isBfdEnabled()) {
            hcl.append(INDENT).append("bfd {\n");
            hcl.append(rawAttr(2, "enabled", "true"));
            hcl.append(attr(2, "interval", String.valueOf(rp.getBfdInterval())));
            hcl.append(INDENT).append("}\n");
        }
    }

    // ---- HCL formatting helpers ----

    /** Emits a quoted string attribute: {@code key = "value"}. */
    private String attr(int depth, String key, String value) {
        return indent(depth) + key + " = " + quote(value) + "\n";
    }

    /** Emits a raw (unquoted) attribute for numbers, booleans, lists, or expressions. */
    private String rawAttr(int depth, String key, String value) {
        return indent(depth) + key + " = " + value + "\n";
    }

    private String comment(int depth, String text) {
        return indent(depth) + "# " + text + "\n";
    }

    private String indent(int depth) {
        return INDENT.repeat(depth);
    }

    private String quote(String value) {
        if (value == null) {
            return "null";
        }
        return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }

    /**
     * Derives a valid, unique Terraform resource label from a display name. Terraform
     * labels must start with a letter/underscore and contain only letters, digits,
     * underscores and dashes; we sanitize and de-duplicate against already-used labels.
     */
    private String uniqueLabel(Iterable<String> existing, String prefix, String name) {
        String sanitized = sanitizeLabel(name);
        String base = prefix + "_" + sanitized;
        String candidate = base;
        int suffix = 2;
        while (contains(existing, candidate)) {
            candidate = base + "_" + suffix++;
        }
        return candidate;
    }

    private boolean contains(Iterable<String> existing, String candidate) {
        for (String e : existing) {
            if (e.equals(candidate)) {
                return true;
            }
        }
        return false;
    }

    private String sanitizeLabel(String name) {
        if (name == null || name.isBlank()) {
            return "resource";
        }
        String cleaned = name.trim().replaceAll("[^A-Za-z0-9_-]", "_");
        // Collapse runs of underscores and trim leading/trailing ones for readability.
        cleaned = cleaned.replaceAll("_{2,}", "_").replaceAll("^_+|_+$", "");
        if (cleaned.isEmpty()) {
            return "resource";
        }
        char first = cleaned.charAt(0);
        if (!Character.isLetter(first) && first != '_') {
            cleaned = "_" + cleaned;
        }
        return cleaned;
    }
}
