package api.equinix.javasdk.design.optimizer.wizard.model;

import api.equinix.javasdk.FabricGateway;
import api.equinix.javasdk.core.waiter.ResourceWaiter;
import api.equinix.javasdk.fabric.enums.CloudRouterState;
import api.equinix.javasdk.fabric.enums.ConnectionState;
import api.equinix.javasdk.fabric.enums.ConnectionType;
import api.equinix.javasdk.fabric.enums.GatewayPackageCode;
import api.equinix.javasdk.fabric.enums.RoutingProtocolType;
import api.equinix.javasdk.fabric.model.CloudRouter;
import api.equinix.javasdk.fabric.model.Connection;
import api.equinix.javasdk.fabric.model.RoutingProtocol;
import api.equinix.javasdk.design.optimizer.model.OptimizationResult;
import api.equinix.javasdk.design.optimizer.wizard.enums.ConnectionPurpose;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Builder;
import lombok.Value;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.stream.Collectors;

/**
 * A complete deployment plan generated by the Deployment Wizard. Contains all
 * planned Cloud Routers, provider connections, backbone links, routing protocols,
 * and aggregated pricing. Supports review via {@link #toMarkdown()}, dry-run
 * validation via {@link #dryRun()}, and full execution via {@link #execute()}.
 */
@Value
@Builder
public class DeploymentPlan {

    OptimizationResult sourceOptimization;

    List<PlannedCloudRouter> cloudRouters;

    List<PlannedConnection> providerConnections;

    List<PlannedBackboneLink> backboneLinks;

    List<PlannedRoutingProtocol> routingProtocols;

    PlanPricing pricing;

    boolean valid;

    List<String> validationErrors;

    @JsonIgnore
    FabricGateway fabric;

    /**
     * Total number of resources that will be created by this plan.
     */
    public int totalResourceCount() {
        int count = 0;
        if (cloudRouters != null) count += cloudRouters.size();
        if (providerConnections != null) count += providerConnections.size();
        if (backboneLinks != null) count += backboneLinks.size();
        if (routingProtocols != null) count += routingProtocols.size();
        return count;
    }

    /**
     * Generates a concise plain-text summary of the deployment plan.
     */
    public String toSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append("Deployment Plan: ");
        sb.append(cloudRouters != null ? cloudRouters.size() : 0).append(" Cloud Router(s), ");
        sb.append(providerConnections != null ? providerConnections.size() : 0).append(" provider connection(s), ");
        sb.append(backboneLinks != null ? backboneLinks.size() : 0).append(" backbone link(s), ");
        sb.append(routingProtocols != null ? routingProtocols.size() : 0).append(" routing protocol(s). ");
        sb.append("Total resources: ").append(totalResourceCount()).append(".");

        if (pricing != null && pricing.getMonthlyTotal() != null) {
            sb.append(" Estimated monthly cost: $").append(pricing.getMonthlyTotal())
                    .append(" ").append(pricing.getCurrency()).append(".");
        }

        if (!valid && validationErrors != null && !validationErrors.isEmpty()) {
            sb.append(" VALIDATION ERRORS: ").append(validationErrors.size());
        }

        return sb.toString();
    }

    /**
     * Generates a full markdown-formatted deployment plan report with bandwidth
     * and pricing tables.
     */
    public String toMarkdown() {
        StringBuilder md = new StringBuilder();
        md.append("# Deployment Plan\n\n");
        md.append("_Generated from optimization computed at ").append(sourceOptimization.getComputedAt()).append("_\n\n");
        md.append("**Total Resources:** ").append(totalResourceCount()).append("\n\n");

        // Validation status
        if (!valid && validationErrors != null && !validationErrors.isEmpty()) {
            md.append("> **VALIDATION ERRORS**\n");
            for (String error : validationErrors) {
                md.append("> - ").append(error).append("\n");
            }
            md.append("\n");
        }

        // Cloud Routers
        if (cloudRouters != null && !cloudRouters.isEmpty()) {
            md.append("## Cloud Routers\n\n");
            md.append("| Name | Metro | Package |\n");
            md.append("|------|-------|---------|\n");
            for (PlannedCloudRouter cr : cloudRouters) {
                md.append("| ").append(cr.getName())
                        .append(" | ").append(cr.getMetroId())
                        .append(" | ").append(cr.getPackageCode())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Provider Connections
        if (providerConnections != null && !providerConnections.isEmpty()) {
            md.append("## Provider Connections\n\n");
            md.append("| Name | Type | A-Side (Metro) | Z-Side (Provider) | Bandwidth | Workload Breakdown |\n");
            md.append("|------|------|----------------|-------------------|-----------|--------------------|\n");
            for (PlannedConnection conn : providerConnections) {
                md.append("| ").append(conn.getName())
                        .append(" | ").append(conn.getConnectionType())
                        .append(" | ").append(conn.getASideRouterName()).append(" (").append(conn.getASideMetro()).append(")")
                        .append(" | ").append(conn.getZSideProviderLabel());
                if (conn.getZSideSellerRegion() != null) {
                    md.append(" [").append(conn.getZSideSellerRegion()).append("]");
                }
                md.append(" | ").append(conn.getBandwidthMbps()).append(" Mbps");
                md.append(" | ");
                if (conn.getBandwidthAllocation() != null && conn.getBandwidthAllocation().getPerWorkload() != null) {
                    md.append(conn.getBandwidthAllocation().getPerWorkload().entrySet().stream()
                            .map(e -> e.getKey() + ": " + e.getValue() + " Mbps")
                            .collect(Collectors.joining(", ")));
                }
                md.append(" |\n");
            }
            md.append("\n");
        }

        // Backbone Links
        if (backboneLinks != null && !backboneLinks.isEmpty()) {
            md.append("## Backbone Links\n\n");
            md.append("| Name | Metro A | Metro Z | Bandwidth | Topology |\n");
            md.append("|------|---------|---------|-----------|----------|\n");
            for (PlannedBackboneLink link : backboneLinks) {
                md.append("| ").append(link.getName())
                        .append(" | ").append(link.getMetroA())
                        .append(" | ").append(link.getMetroZ())
                        .append(" | ").append(link.getBandwidthMbps()).append(" Mbps")
                        .append(" | ").append(link.getTopology())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Routing Protocols
        if (routingProtocols != null && !routingProtocols.isEmpty()) {
            md.append("## Routing Protocols\n\n");
            md.append("| Connection | Type | Customer Peer | Equinix Peer | ASN | BFD |\n");
            md.append("|------------|------|---------------|--------------|-----|-----|\n");
            for (PlannedRoutingProtocol rp : routingProtocols) {
                md.append("| ").append(rp.getConnectionName())
                        .append(" | ").append(rp.getType())
                        .append(" | ").append(rp.getCustomerPeerIpv4() != null ? rp.getCustomerPeerIpv4() : "-")
                        .append(" | ").append(rp.getEquinixPeerIpv4() != null ? rp.getEquinixPeerIpv4() : rp.getEquinixIfaceIpv4())
                        .append(" | ").append(rp.getCustomerAsn() != null ? rp.getCustomerAsn() : "-")
                        .append(" | ").append(rp.isBfdEnabled() ? rp.getBfdInterval() + "ms" : "off")
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Pricing
        if (pricing != null) {
            md.append("## Cost Estimate\n\n");
            md.append("| Category | Monthly Cost |\n");
            md.append("|----------|-------------:|\n");
            if (pricing.getRouterMonthlyCost() != null) {
                md.append("| Cloud Routers | $").append(pricing.getRouterMonthlyCost()).append(" |\n");
            }
            if (pricing.getProviderConnectionMonthlyCost() != null) {
                md.append("| Provider Connections | $").append(pricing.getProviderConnectionMonthlyCost()).append(" |\n");
            }
            if (pricing.getBackboneMonthlyCost() != null) {
                md.append("| Backbone Links | $").append(pricing.getBackboneMonthlyCost()).append(" |\n");
            }
            if (pricing.getMonthlyTotal() != null) {
                md.append("| **Total Monthly** | **$").append(pricing.getMonthlyTotal()).append("** |\n");
            }
            if (pricing.getSetupTotal() != null) {
                md.append("| Setup (one-time) | $").append(pricing.getSetupTotal()).append(" |\n");
            }
            md.append("\n_").append(pricing.getDisclaimer()).append("_\n\n");
        }

        // Execution instructions
        md.append("## Execution\n\n");
        md.append("Resources will be created in this order:\n\n");
        md.append("1. Cloud Routers (").append(cloudRouters != null ? cloudRouters.size() : 0).append(")\n");
        md.append("2. Provider Connections (").append(providerConnections != null ? providerConnections.size() : 0).append(")\n");
        md.append("3. Backbone Links (").append(backboneLinks != null ? backboneLinks.size() : 0).append(")\n");
        md.append("4. Routing Protocols (").append(routingProtocols != null ? routingProtocols.size() : 0).append(")\n\n");
        md.append("Call `plan.dryRun()` to validate, or `plan.execute()` to provision all resources.\n");

        return md.toString();
    }

    /**
     * Begins a value-realization assessment of this plan: declare your per-provider
     * monthly egress volumes and get back the egress savings the plan's private
     * interconnects unlock, netted against the plan's actual interconnect cost.
     *
     * <pre>{@code
     * PlanValueRealization vr = plan.valueRealization()
     *     .egress(CloudProviderType.AWS, 50, DataUnit.TERABYTE)
     *     .assess();
     * System.out.println(vr.toMarkdown());
     * }</pre>
     *
     * @return a {@link PlanValueAssessment} builder for declaring egress volumes
     */
    public PlanValueAssessment valueRealization() {
        return new PlanValueAssessment(this);
    }

    /**
     * Validates the deployment plan using Fabric's dry-run API.
     * Returns a new DeploymentPlan with updated validation status.
     */
    public DeploymentPlan dryRun() {
        List<String> errors = new ArrayList<>();

        // Validate Cloud Routers with client-side field checks only. Cloud Router creation has no
        // dry-run mode, and calling create() here would provision live, billable routers — which a
        // dry run must never do — so we validate the required fields instead.
        if (cloudRouters != null) {
            for (PlannedCloudRouter cr : cloudRouters) {
                if (cr.getName() == null || cr.getName().isBlank()) {
                    errors.add("Cloud Router: missing name");
                }
                if (cr.getMetroId() == null) {
                    errors.add("Cloud Router '" + cr.getName() + "': missing metro");
                }
                if (cr.getPackageCode() == null || cr.getPackageCode().isBlank()) {
                    errors.add("Cloud Router '" + cr.getName() + "': missing package code");
                }
            }
        }

        // Validate connections
        if (providerConnections != null) {
            for (PlannedConnection conn : providerConnections) {
                try {
                    fabric.connections().define(conn.getConnectionType())
                            .name(conn.getName())
                            .bandwidth(conn.getBandwidthMbps())
                            .dryRun()
                            .create();
                }
                catch (Exception e) {
                    errors.add("Connection '" + conn.getName() + "': " + e.getMessage());
                }
            }
        }

        return DeploymentPlan.builder()
                .sourceOptimization(sourceOptimization)
                .cloudRouters(cloudRouters)
                .providerConnections(providerConnections)
                .backboneLinks(backboneLinks)
                .routingProtocols(routingProtocols)
                .pricing(pricing)
                .valid(errors.isEmpty())
                .validationErrors(errors)
                .fabric(fabric)
                .build();
    }

    /**
     * Executes the deployment plan, creating all resources in the correct order:
     * Cloud Routers, then provider connections, then backbone links, then routing protocols.
     *
     * <p>Errors are captured in the outcome rather than thrown, allowing partial
     * deployments to be inspected and retried.</p>
     *
     * @return the execution outcome with all provisioned resources and any errors
     */
    public DeploymentOutcome execute() {
        long startTime = System.currentTimeMillis();
        List<ProvisionedResource> resources = new ArrayList<>();
        List<ProvisioningError> errors = new ArrayList<>();
        Map<String, String> routerUuids = new HashMap<>();
        Map<String, String> connectionUuids = new HashMap<>();

        // Phase 1: Create Cloud Routers
        if (cloudRouters != null) {
            for (PlannedCloudRouter planned : cloudRouters) {
                try {
                    CloudRouter cr = fabric.cloudRouters().define()
                            .name(planned.getName())
                            .inMetro(planned.getMetroId().code())
                            .withPackage(GatewayPackageCode.valueOf(planned.getPackageCode()))
                            .accountNumber(planned.getAccountNumber())
                            .projectId(planned.getProjectId())
                            .create();

                    routerUuids.put(planned.getName(), cr.getUuid());
                    // Wait for the router to become active before the connections (and the routing
                    // protocols built on them) that depend on it are created — provisioning is async,
                    // and building a dependent against a still-provisioning router fails.
                    String state = awaitState(() -> fabric.cloudRouters().getByUuid(cr.getUuid()),
                            CloudRouter::getState, CloudRouterState.PROVISIONED,
                            Set.of(CloudRouterState.NOT_PROVISIONED, CloudRouterState.DEPROVISIONED));
                    if (state == null) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("CloudRouter")
                                .resourceName(planned.getName())
                                .reason("did not reach PROVISIONED within the timeout")
                                .recoverable(true)
                                .build());
                    }
                    resources.add(ProvisionedResource.builder()
                            .resourceType("CloudRouter")
                            .name(planned.getName())
                            .uuid(cr.getUuid())
                            .metroId(planned.getMetroId())
                            .status(state != null ? state : "PROVISIONING")
                            .build());
                }
                catch (Exception e) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("CloudRouter")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                }
            }
        }

        // Phase 2: Create Provider Connections
        if (providerConnections != null) {
            for (PlannedConnection planned : providerConnections) {
                try {
                    Connection conn = fabric.connections().define(planned.getConnectionType())
                            .name(planned.getName())
                            .bandwidth(planned.getBandwidthMbps())
                            .create();

                    connectionUuids.put(planned.getName(), conn.getUuid());
                    String state = awaitState(() -> fabric.connections().getByUuid(conn.getUuid()),
                            Connection::getState, ConnectionState.PROVISIONED, Set.of());
                    if (state == null) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("Connection")
                                .resourceName(planned.getName())
                                .reason("did not reach PROVISIONED within the timeout")
                                .recoverable(true)
                                .build());
                    }
                    resources.add(ProvisionedResource.builder()
                            .resourceType("Connection")
                            .name(planned.getName())
                            .uuid(conn.getUuid())
                            .metroId(planned.getASideMetro())
                            .status(state != null ? state : "PROVISIONING")
                            .build());
                }
                catch (Exception e) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("Connection")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                }
            }
        }

        // Phase 3: Create Backbone Links
        if (backboneLinks != null) {
            for (PlannedBackboneLink link : backboneLinks) {
                PlannedConnection planned = link.getConnection();
                try {
                    Connection conn = fabric.connections().define(planned.getConnectionType())
                            .name(planned.getName())
                            .bandwidth(planned.getBandwidthMbps())
                            .create();

                    connectionUuids.put(planned.getName(), conn.getUuid());
                    String state = awaitState(() -> fabric.connections().getByUuid(conn.getUuid()),
                            Connection::getState, ConnectionState.PROVISIONED, Set.of());
                    if (state == null) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("BackboneLink")
                                .resourceName(planned.getName())
                                .reason("did not reach PROVISIONED within the timeout")
                                .recoverable(true)
                                .build());
                    }
                    resources.add(ProvisionedResource.builder()
                            .resourceType("BackboneLink")
                            .name(planned.getName())
                            .uuid(conn.getUuid())
                            .metroId(link.getMetroA())
                            .status(state != null ? state : "PROVISIONING")
                            .build());
                }
                catch (Exception e) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("BackboneLink")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                }
            }
        }

        // Phase 4: Create Routing Protocols
        if (routingProtocols != null) {
            for (PlannedRoutingProtocol planned : routingProtocols) {
                String connectionUuid = connectionUuids.get(planned.getConnectionName());
                if (connectionUuid == null) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("RoutingProtocol")
                            .resourceName(planned.getName())
                            .reason("Parent connection '" + planned.getConnectionName() + "' was not provisioned")
                            .recoverable(false)
                            .build());
                    continue;
                }
                try {
                    var rpBuilder = fabric.routingProtocols().define()
                            .ofType(planned.getType())
                            .withName(planned.getName());

                    if (planned.getType() == RoutingProtocolType.BGP) {
                        rpBuilder.withCustomerAsn(planned.getCustomerAsn())
                                .withBGPIpv4(planned.getCustomerPeerIpv4(), planned.getEquinixPeerIpv4(), true)
                                .withBFD(planned.isBfdEnabled(), planned.getBfdInterval());
                    }
                    else if (planned.getType() == RoutingProtocolType.DIRECT) {
                        rpBuilder.withDirectIpv4(planned.getEquinixIfaceIpv4());
                    }

                    RoutingProtocol rp = rpBuilder.create(connectionUuid);
                    resources.add(ProvisionedResource.builder()
                            .resourceType("RoutingProtocol")
                            .name(planned.getName())
                            .uuid(rp.getUuid())
                            .status("PROVISIONED")
                            .build());
                }
                catch (Exception e) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("RoutingProtocol")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                }
            }
        }

        long elapsed = System.currentTimeMillis() - startTime;
        return DeploymentOutcome.builder()
                .plan(this)
                .resources(resources)
                .fullySuccessful(errors.isEmpty())
                .errors(errors)
                .executionTimeMs(elapsed)
                .build();
    }

    /**
     * Polls the given resource until it reaches {@code ready}, hits one of {@code terminalFailures},
     * or the timeout (5 minutes, polled every 5 seconds) elapses. Returns the resource's state name
     * once ready, or {@code null} if it failed or timed out — letting {@link #execute()} record a
     * recoverable error and the actual interim status rather than asserting a state that never held.
     */
    private static <T, S extends Enum<S>> String awaitState(Supplier<T> fetch, Function<T, S> state,
                                                             S ready, Set<S> terminalFailures) {
        try {
            T resource = ResourceWaiter.forResource(fetch)
                    .until(r -> state.apply(r) == ready)
                    .failWhen(r -> terminalFailures.contains(state.apply(r)))
                    .timeout(Duration.ofMinutes(5))
                    .pollInterval(Duration.ofSeconds(5))
                    .await();
            return state.apply(resource).name();
        }
        catch (RuntimeException e) {
            // WaiterTimeoutException / WaiterFailedException (or a fetch error) — not ready.
            return null;
        }
    }

    /**
     * Best-effort teardown of the resources provisioned by a prior {@link #execute()}: deletes the
     * connections (and backbone links), then the Cloud Routers, in reverse dependency order. Routing
     * protocols are removed with their parent connection. Use this to clean up a partially-failed
     * deployment rather than leaving orphaned, billable resources behind.
     *
     * @param outcome the outcome returned by {@link #execute()}
     * @return the deletions that failed (empty when the rollback was clean)
     */
    public List<ProvisioningError> rollback(DeploymentOutcome outcome) {
        List<ProvisioningError> failures = new ArrayList<>();
        if (outcome == null || outcome.getResources() == null) {
            return failures;
        }
        List<ProvisionedResource> reversed = new ArrayList<>(outcome.getResources());
        Collections.reverse(reversed);
        for (ProvisionedResource resource : reversed) {
            if (resource.getUuid() == null) {
                continue;
            }
            try {
                switch (resource.getResourceType()) {
                    case "Connection":
                    case "BackboneLink":
                        fabric.connections().getByUuid(resource.getUuid()).delete();
                        break;
                    case "CloudRouter":
                        fabric.cloudRouters().getByUuid(resource.getUuid()).delete();
                        break;
                    default:
                        // RoutingProtocol and any others are removed with their parent connection.
                        break;
                }
            }
            catch (RuntimeException e) {
                failures.add(ProvisioningError.builder()
                        .resourceType(resource.getResourceType())
                        .resourceName(resource.getName())
                        .reason("rollback delete failed: " + e.getMessage())
                        .recoverable(false)
                        .build());
            }
        }
        return failures;
    }
}
