package com.eqixiac.equinix.design.optimizer.wizard.model;

import com.eqixiac.equinix.FabricGateway;
import com.eqixiac.equinix.core.waiter.ResourceWaiter;
import com.eqixiac.equinix.core.waiter.WaiterFailedException;
import com.eqixiac.equinix.fabric.enums.CloudRouterState;
import com.eqixiac.equinix.fabric.enums.ConnectionState;
import com.eqixiac.equinix.fabric.enums.GatewayPackageCode;
import com.eqixiac.equinix.fabric.enums.PeeringType;
import com.eqixiac.equinix.fabric.enums.RoutingProtocolType;
import com.eqixiac.equinix.fabric.model.CloudRouter;
import com.eqixiac.equinix.fabric.model.Connection;
import com.eqixiac.equinix.fabric.model.RoutingProtocol;
import com.eqixiac.equinix.fabric.model.implementation.cloud.CloudProviderType;
import com.eqixiac.equinix.fabric.model.json.creators.ConnectionOperator;
import com.eqixiac.equinix.design.optimizer.model.OptimizationResult;
import com.eqixiac.equinix.design.optimizer.wizard.PlanValidator;
import com.eqixiac.equinix.design.optimizer.wizard.enums.ConnectionPurpose;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Builder;
import lombok.Value;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.stream.Collectors;

/**
 * A complete deployment plan generated by the Deployment Wizard. Contains all
 * planned Cloud Routers, provider connections, backbone links, routing protocols,
 * and aggregated pricing. Supports review via {@link #toMarkdown()}, dry-run
 * validation via {@link #dryRun()}, and full execution via {@link #execute()}.
 */
@Value
@Builder(toBuilder = true)
public class DeploymentPlan {

    OptimizationResult sourceOptimization;

    List<PlannedCloudRouter> cloudRouters;

    List<PlannedConnection> providerConnections;

    List<PlannedBackboneLink> backboneLinks;

    List<PlannedRoutingProtocol> routingProtocols;

    PlanPricing pricing;

    boolean valid;

    List<String> validationErrors;

    /**
     * Validations that could NOT be completed at plan time and will run at provisioning — chiefly the
     * live connection endpoint dry-run, which needs the target Cloud Router (which does not exist yet)
     * and the customer's cloud authorization keys. These are <em>not</em> errors: a structurally-fine
     * plan is valid with items here, and each note says what will be validated and what to gather.
     */
    List<String> deferredValidations;

    /**
     * Validations that could NOT be attempted at plan time — an infeasibility, never a plan defect: a
     * live surface was unavailable (an offline / bare-stub run), or the API answered a live dry-run with
     * a non-rejection failure (401/403 not entitled — the brand-new-customer case, 429 throttled, 5xx
     * server-side, or a transport/timeout error). Each entry is a human/LLM-readable reason. These are
     * <em>not</em> errors: a structurally-fine plan stays {@link #valid} with items here, and each note
     * says exactly what could not be checked and why, so the gap is called out rather than hidden.
     */
    List<String> skippedValidations;

    /**
     * The per-connection authorization a customer must gather before each provider connection can be
     * provisioned (the cloud-specific key, the VLAN tag, and — for Azure — the peering type). Populated
     * for every provider connection so a brand-new customer sees exactly what to collect.
     */
    List<ConnectionInputRequirement> requiredInputs;

    @JsonIgnore
    FabricGateway fabric;

    /**
     * Total number of resources that will be created by this plan.
     */
    public int totalResourceCount() {
        int count = 0;
        if (cloudRouters != null) count += cloudRouters.size();
        if (providerConnections != null) count += providerConnections.size();
        if (backboneLinks != null) count += backboneLinks.size();
        if (routingProtocols != null) count += routingProtocols.size();
        return count;
    }

    /**
     * Generates a concise plain-text summary of the deployment plan.
     */
    public String toSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append("Deployment Plan: ");
        sb.append(cloudRouters != null ? cloudRouters.size() : 0).append(" Cloud Router(s), ");
        sb.append(providerConnections != null ? providerConnections.size() : 0).append(" provider connection(s), ");
        sb.append(backboneLinks != null ? backboneLinks.size() : 0).append(" backbone link(s), ");
        sb.append(routingProtocols != null ? routingProtocols.size() : 0).append(" routing protocol(s). ");
        sb.append("Total resources: ").append(totalResourceCount()).append(".");

        // Money always renders with its ACTUAL currency (mirroring OptimizationResult.money) — a
        // hardcoded "$" next to a EUR figure misstated the amount by the exchange rate.
        if (pricing != null && pricing.getMonthlyTotal() != null) {
            sb.append(" Estimated monthly cost: ")
                    .append(money(pricing.getMonthlyTotal(), pricing.getCurrency())).append(".");
        }
        else if (pricing != null && pricing.getMonthlyByCurrency() != null
                && pricing.getMonthlyByCurrency().size() > 1) {
            sb.append(" Estimated monthly cost spans multiple currencies: ")
                    .append(describeByCurrency(pricing.getMonthlyByCurrency()))
                    .append(" (no single-currency total).");
        }

        if (!valid && validationErrors != null && !validationErrors.isEmpty()) {
            sb.append(" VALIDATION ERRORS: ").append(validationErrors.size());
        }

        if (deferredValidations != null && !deferredValidations.isEmpty()) {
            sb.append(" DEFERRED TO PROVISIONING: ").append(deferredValidations.size())
                    .append(" (validated at provisioning; needs your authorization keys).");
        }

        if (skippedValidations != null && !skippedValidations.isEmpty()) {
            sb.append(" SKIPPED (could not validate now): ").append(skippedValidations.size())
                    .append(" (offline or the API could not be reached — see the reasons).");
        }

        long roundedUp = providerConnections == null ? 0 : providerConnections.stream()
                .filter(c -> c.getProfileSelection() != null && c.getProfileSelection().isRoundedUp())
                .count();
        if (roundedUp > 0) {
            sb.append(" BANDWIDTH ROUNDED UP: ").append(roundedUp)
                    .append(" connection(s) to the nearest service-profile tier (raises billed bandwidth).");
        }

        return sb.toString();
    }

    /**
     * Generates a full markdown-formatted deployment plan report with bandwidth
     * and pricing tables.
     */
    public String toMarkdown() {
        StringBuilder md = new StringBuilder();
        md.append("# Deployment Plan\n\n");
        md.append("_Generated from optimization computed at ").append(sourceOptimization.getComputedAt()).append("_\n\n");
        md.append("**Total Resources:** ").append(totalResourceCount()).append("\n\n");

        // Validation status — validated now (structural + router dry-run).
        if (!valid && validationErrors != null && !validationErrors.isEmpty()) {
            md.append("> **VALIDATION ERRORS** (validated now — structural + router dry-run)\n");
            for (String error : validationErrors) {
                md.append("> - ").append(error).append("\n");
            }
            md.append("\n");
        }

        // Deferred to provisioning — the live connection endpoint dry-run (needs the target Cloud
        // Router to exist and the customer's authorization keys). These are NOT errors.
        if (deferredValidations != null && !deferredValidations.isEmpty()) {
            md.append("> **DEFERRED TO PROVISIONING** — the live connection endpoint dry-run runs when the "
                    + "plan is applied (needs your authorization keys)\n");
            for (String note : deferredValidations) {
                md.append("> - ").append(note).append("\n");
            }
            md.append("\n");
        }

        // Skipped — validations that could NOT be attempted now (an offline/bare-stub run, or the API
        // answered a live dry-run with a non-rejection failure such as 403/429/5xx/timeout). These are
        // NOT errors: each note says what could not be checked and why, so the gap is called out.
        if (skippedValidations != null && !skippedValidations.isEmpty()) {
            md.append("> **SKIPPED (could not validate now)** — these checks could not be attempted; "
                    + "each reason says why. They do not invalidate the plan.\n");
            for (String note : skippedValidations) {
                md.append("> - ").append(note).append("\n");
            }
            md.append("\n");
        }

        // Bandwidth round-up + profile choice — surfaced, never silent, since rounding up raises the
        // billed bandwidth and several profiles may cover a connection in different ways.
        appendBandwidthSelectionNotes(md);

        // Required customer inputs — what a first-time customer must gather before provisioning.
        if (requiredInputs != null && !requiredInputs.isEmpty()) {
            md.append("## Required Customer Inputs (before provisioning)\n\n");
            md.append("| Connection | Provider | Authorization key | VLAN | Azure peering |\n");
            md.append("|------------|----------|-------------------|------|---------------|\n");
            for (ConnectionInputRequirement req : requiredInputs) {
                md.append("| ").append(req.getConnectionName())
                        .append(" | ").append(req.getProviderLabel() != null ? req.getProviderLabel() : "-")
                        .append(" | ");
                if (req.isAuthenticationKeyRequired()) {
                    md.append(req.getAuthenticationKeyLabel())
                            .append(req.isAuthenticationKeyProvided() ? " (provided)" : "");
                } else {
                    md.append("-");
                }
                md.append(" | ").append(req.isVlanTagRequired() ? "required" : "-")
                        .append(" | ").append(req.isPeeringTypeRequired() ? "required" : "-")
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Cloud Routers
        if (cloudRouters != null && !cloudRouters.isEmpty()) {
            md.append("## Cloud Routers\n\n");
            md.append("| Name | Metro | Package |\n");
            md.append("|------|-------|---------|\n");
            for (PlannedCloudRouter cr : cloudRouters) {
                md.append("| ").append(cr.getName())
                        .append(" | ").append(cr.getMetroId())
                        .append(" | ").append(cr.getPackageCode())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Provider Connections
        if (providerConnections != null && !providerConnections.isEmpty()) {
            md.append("## Provider Connections\n\n");
            md.append("| Name | Type | A-Side (Metro) | Z-Side (Provider) | Bandwidth | Workload Breakdown |\n");
            md.append("|------|------|----------------|-------------------|-----------|--------------------|\n");
            for (PlannedConnection conn : providerConnections) {
                md.append("| ").append(conn.getName())
                        .append(" | ").append(conn.getConnectionType())
                        .append(" | ").append(conn.getASideRouterName()).append(" (").append(conn.getASideMetro()).append(")")
                        .append(" | ").append(conn.getZSideProviderLabel());
                if (conn.getZSideSellerRegion() != null) {
                    md.append(" [").append(conn.getZSideSellerRegion()).append("]");
                }
                md.append(" | ").append(conn.getBandwidthMbps()).append(" Mbps");
                ProfileSelection sel = conn.getProfileSelection();
                if (sel != null && sel.isRoundedUp()) {
                    md.append(" (rounded up from ").append(sel.getRequestedMbps()).append(")");
                }
                md.append(" | ");
                if (conn.getBandwidthAllocation() != null && conn.getBandwidthAllocation().getPerWorkload() != null) {
                    md.append(conn.getBandwidthAllocation().getPerWorkload().entrySet().stream()
                            .map(e -> e.getKey() + ": " + e.getValue() + " Mbps")
                            .collect(Collectors.joining(", ")));
                }
                md.append(" |\n");
            }
            md.append("\n");
        }

        // Backbone Links
        if (backboneLinks != null && !backboneLinks.isEmpty()) {
            md.append("## Backbone Links\n\n");
            md.append("| Name | Metro A | Metro Z | Bandwidth | Topology |\n");
            md.append("|------|---------|---------|-----------|----------|\n");
            for (PlannedBackboneLink link : backboneLinks) {
                md.append("| ").append(link.getName())
                        .append(" | ").append(link.getMetroA())
                        .append(" | ").append(link.getMetroZ())
                        .append(" | ").append(link.getBandwidthMbps()).append(" Mbps")
                        .append(" | ").append(link.getTopology())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Routing Protocols
        if (routingProtocols != null && !routingProtocols.isEmpty()) {
            md.append("## Routing Protocols\n\n");
            md.append("| Connection | Type | Customer Peer | Equinix Peer | ASN | BFD |\n");
            md.append("|------------|------|---------------|--------------|-----|-----|\n");
            for (PlannedRoutingProtocol rp : routingProtocols) {
                md.append("| ").append(rp.getConnectionName())
                        .append(" | ").append(rp.getType())
                        .append(" | ").append(rp.getCustomerPeerIpv4() != null ? rp.getCustomerPeerIpv4() : "-")
                        .append(" | ").append(rp.getEquinixPeerIpv4() != null ? rp.getEquinixPeerIpv4() : rp.getEquinixIfaceIpv4())
                        .append(" | ").append(rp.getCustomerAsn() != null ? rp.getCustomerAsn() : "-")
                        .append(" | ").append(rp.isBfdEnabled() ? rp.getBfdInterval() + "ms" : "off")
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Pricing. Every figure renders with its ACTUAL currency (mirroring OptimizationResult.money)
        // — never a hardcoded "$", which misstated any non-USD amount by the exchange rate. A category
        // that itself spans currencies carries no single figure; its per-currency subtotals are shown.
        if (pricing != null) {
            md.append("## Cost Estimate\n\n");
            md.append("| Category | Monthly Cost |\n");
            md.append("|----------|-------------:|\n");
            appendCostRow(md, "Cloud Routers", pricing.getRouterMonthlyCost(),
                    pricing.getRouterCurrency(), pricing.getRouterMonthlyByCurrency());
            appendCostRow(md, "Provider Connections", pricing.getProviderConnectionMonthlyCost(),
                    pricing.getProviderConnectionCurrency(), pricing.getProviderConnectionMonthlyByCurrency());
            appendCostRow(md, "Backbone Links", pricing.getBackboneMonthlyCost(),
                    pricing.getBackboneCurrency(), pricing.getBackboneMonthlyByCurrency());
            if (pricing.getMonthlyTotal() != null) {
                md.append("| **Total Monthly** | **")
                        .append(money(pricing.getMonthlyTotal(), pricing.getCurrency())).append("** |\n");
            }
            else if (pricing.getMonthlyByCurrency() != null && pricing.getMonthlyByCurrency().size() > 1) {
                md.append("| **Total Monthly** | **")
                        .append(describeByCurrency(pricing.getMonthlyByCurrency()))
                        .append("** (multiple currencies — no single total) |\n");
            }
            if (pricing.getSetupTotal() != null) {
                md.append("| Setup (one-time) | ")
                        .append(money(pricing.getSetupTotal(), pricing.getCurrency())).append(" |\n");
            }
            md.append("\n_").append(pricing.getDisclaimer()).append("_\n\n");
        }

        // Execution instructions
        md.append("## Execution\n\n");
        md.append("Resources will be created in this order:\n\n");
        md.append("1. Cloud Routers (").append(cloudRouters != null ? cloudRouters.size() : 0).append(")\n");
        md.append("2. Provider Connections (").append(providerConnections != null ? providerConnections.size() : 0).append(")\n");
        md.append("3. Backbone Links (").append(backboneLinks != null ? backboneLinks.size() : 0).append(")\n");
        md.append("4. Routing Protocols (").append(routingProtocols != null ? routingProtocols.size() : 0).append(")\n\n");
        md.append("Call `plan.dryRun()` to validate, or `plan.execute()` to provision all resources.\n");

        return md.toString();
    }

    /**
     * Appends one Cost Estimate row: the single-currency figure rendered with its actual currency
     * when the category reconciled, otherwise the category's per-currency subtotals (a mixed
     * category has no single figure). Emits nothing when the category has neither.
     */
    private static void appendCostRow(StringBuilder md, String label, BigDecimal cost,
                                      String currency, Map<String, BigDecimal> byCurrency) {
        if (cost != null) {
            md.append("| ").append(label).append(" | ").append(money(cost, currency)).append(" |\n");
        }
        else if (byCurrency != null && !byCurrency.isEmpty()) {
            md.append("| ").append(label).append(" | ").append(describeByCurrency(byCurrency))
                    .append(" (multiple currencies) |\n");
        }
    }

    /**
     * Renders a monetary amount with the symbol of its actual currency ({@code "$2300.00"},
     * {@code "€1800.00"}), falling back to {@code "<amount> <code>"} when the code has no distinct
     * symbol or is unknown, and to the bare amount when no currency was stated at all. Mirrors
     * {@code OptimizationResult.money} and replaces the former hardcoded {@code "$"}, which asserted
     * US dollars against figures that live Fabric pricing legitimately quotes in other currencies.
     */
    private static String money(BigDecimal amount, String currency) {
        if (amount == null) {
            return "unavailable";
        }
        if (currency == null || currency.isBlank()) {
            return amount.toPlainString();
        }
        try {
            String symbol = java.util.Currency.getInstance(currency).getSymbol(java.util.Locale.US);
            if (!symbol.equals(currency)) {
                return symbol + amount.toPlainString();
            }
        }
        catch (IllegalArgumentException notIso4217) {
            // Not an ISO 4217 code: fall through to the "<amount> <code>" form below.
        }
        return amount.toPlainString() + " " + currency;
    }

    /**
     * Renders a per-currency breakdown, e.g. {@code "USD 2300.00, EUR 1800.00"}, used wherever
     * amounts span currencies and no single aggregate figure exists.
     */
    private static String describeByCurrency(Map<String, BigDecimal> byCurrency) {
        if (byCurrency == null || byCurrency.isEmpty()) {
            return "unavailable";
        }
        return byCurrency.entrySet().stream()
                .map(e -> e.getKey() + " " + e.getValue().toPlainString())
                .collect(Collectors.joining(", "));
    }

    /**
     * Appends the bandwidth round-up and profile-choice notes to the markdown report. A round-up raises
     * the billed bandwidth, so it is called out with the requirement, the billed tier, and the increase;
     * a connection with more than one covering profile is called out as a decision point (the default is
     * used, but the alternatives are named for review). Emits nothing when neither applies.
     */
    private void appendBandwidthSelectionNotes(StringBuilder md) {
        if (providerConnections == null || providerConnections.isEmpty()) {
            return;
        }
        List<PlannedConnection> roundedUp = new ArrayList<>();
        List<PlannedConnection> multiChoice = new ArrayList<>();
        for (PlannedConnection conn : providerConnections) {
            ProfileSelection sel = conn.getProfileSelection();
            if (sel == null) {
                continue;
            }
            if (sel.isRoundedUp()) {
                roundedUp.add(conn);
            }
            if (sel.hasChoice()) {
                multiChoice.add(conn);
            }
        }
        if (roundedUp.isEmpty() && multiChoice.isEmpty()) {
            return;
        }
        if (!roundedUp.isEmpty()) {
            md.append("> **BANDWIDTH ROUNDED UP** — a requirement with no exact service-profile tier was "
                    + "rounded up to the smallest tier that satisfies it (this raises the billed bandwidth)\n");
            for (PlannedConnection conn : roundedUp) {
                ProfileSelection sel = conn.getProfileSelection();
                md.append("> - ").append(conn.getName()).append(": ")
                        .append(sel.getRequestedMbps()).append(" → ").append(sel.getSelectedTierMbps())
                        .append(" Mbps (+").append(sel.roundedUpByMbps()).append(" Mbps billable)\n");
            }
            md.append("\n");
        }
        if (!multiChoice.isEmpty()) {
            md.append("> **PROFILE CHOICE** — more than one service profile can carry these connections; "
                    + "the tightest-fitting default is used, and the alternatives are available to choose\n");
            for (PlannedConnection conn : multiChoice) {
                ProfileSelection sel = conn.getProfileSelection();
                String alts = sel.getAlternatives().stream()
                        .map(c -> c.getServiceProfileUuid() + " @ " + c.getCoveringTierMbps() + " Mbps")
                        .collect(Collectors.joining(", "));
                md.append("> - ").append(conn.getName()).append(": default ")
                        .append(sel.getSelectedProfileUuid()).append("; options: ").append(alts).append("\n");
            }
            md.append("\n");
        }
    }

    /**
     * Begins a value-realization assessment of this plan: declare your per-provider
     * monthly egress volumes and get back the egress savings the plan's private
     * interconnects unlock, netted against the plan's actual interconnect cost.
     *
     * <pre>{@code
     * PlanValueRealization vr = plan.valueRealization()
     *     .egress(CloudProviderType.AWS, 50, DataUnit.TERABYTE)
     *     .assess();
     * System.out.println(vr.toMarkdown());
     * }</pre>
     *
     * @return a {@link PlanValueAssessment} builder for declaring egress volumes
     */
    public PlanValueAssessment valueRealization() {
        return new PlanValueAssessment(this);
    }

    /**
     * Re-runs the layered plan-time validation and returns a new plan with the refreshed status.
     *
     * <p>This is the same validation the wizard runs when it builds the plan: Layer&nbsp;1 structural +
     * catalog checks, Layer&nbsp;2 live Cloud Router dry-run ({@code POST /routers?dryRun=true}), and
     * Layer&nbsp;3 connection endpoint dispatch — a connection whose A-side Cloud Router does not exist
     * yet is recorded as <em>deferred</em> (its live endpoint dry-run runs at provisioning, and needs
     * your authorization keys) rather than sent a doomed endpoint-less dry-run, while a connection with
     * a pre-existing endpoint is dry-run for real. Nothing is provisioned: the router dry-run creates
     * nothing, and to-be-created connections are never posted here.</p>
     *
     * <p>A live step that cannot be attempted — an offline / bare-stub run, or a live dry-run that the
     * API answers with a non-rejection failure (403 not entitled, 429 throttled, 5xx, or a
     * transport/timeout error) — is recorded as a <em>skipped</em> validation with a reason, never
     * folded into the errors that invalidate the plan. Only a genuine rejection of a well-formed request
     * (a 4xx validation rejection) is an error.</p>
     *
     * @return a new {@link DeploymentPlan} with refreshed validity, deferred validations, skipped
     *         validations, and the required customer inputs
     */
    public DeploymentPlan dryRun() {
        PlanValidator.Result result = PlanValidator.validate(
                sourceOptimization != null ? sourceOptimization.getRecommendations() : null,
                sourceOptimization != null ? sourceOptimization.getRequest() : null,
                sourceOptimization != null ? sourceOptimization.getTopology() : null,
                cloudRouters,
                providerConnections,
                backboneLinks,
                routingProtocols,
                deriveCustomerAsn(),
                fabric);

        return DeploymentPlan.builder()
                .sourceOptimization(sourceOptimization)
                .cloudRouters(cloudRouters)
                .providerConnections(providerConnections)
                .backboneLinks(backboneLinks)
                .routingProtocols(routingProtocols)
                .pricing(pricing)
                .valid(result.errors.isEmpty())
                .validationErrors(result.errors)
                .deferredValidations(result.deferred)
                .skippedValidations(result.skipped)
                .requiredInputs(result.requiredInputs)
                .fabric(fabric)
                .build();
    }

    /**
     * The customer ASN to sanity-check, read from the first BGP routing protocol that carries one
     * (the plan does not store the wizard configuration, but every BGP protocol was stamped with it).
     */
    private Long deriveCustomerAsn() {
        if (routingProtocols == null) {
            return null;
        }
        return routingProtocols.stream()
                .map(PlannedRoutingProtocol::getCustomerAsn)
                .filter(java.util.Objects::nonNull)
                .findFirst()
                .orElse(null);
    }

    /**
     * Executes the deployment plan with no extra customer inputs — for a backbone-only plan, or a plan
     * whose provider connections already carry their own authorization keys. Equivalent to
     * {@link #execute(ExecutionInputs) execute(ExecutionInputs.none())}: a provider connection that
     * still needs a cloud authorization key fails fast (nothing is provisioned) naming the key to
     * gather.
     *
     * @return the execution outcome with all provisioned resources and any errors
     * @see #execute(ExecutionInputs)
     */
    public DeploymentOutcome execute() {
        return execute(ExecutionInputs.none());
    }

    /**
     * Executes the deployment plan, creating all resources in the correct order: Cloud Routers, then
     * provider connections, then backbone links, then routing protocols.
     *
     * <p><b>Execution-time connection pre-flight (Layer&nbsp;3a).</b> A provider connection's live
     * endpoint dry-run cannot run at plan time because its A-side Cloud Router does not exist yet; it
     * runs <em>here</em>, at the only point it is possible. For each connection, once its A-side FCR is
     * provisioned and its real uuid is known, a full connection body — real A-side uuid, Z-side service
     * profile + seller region + the customer's authorization key, DOT1Q VLAN — is
     * {@link ConnectionOperator.ConnectionBuilder#dryRun() dry-run} against the live API; only if the
     * dry-run passes is the connection created for real. A dry-run <em>rejection</em> of a well-formed
     * request (a 4xx validation rejection, e.g. HTTP 400/409) aborts the run and rolls back everything
     * already provisioned (LIFO), so a broken plan never leaves billable Cloud Routers stranded.</p>
     *
     * <p><b>Pre-flight infeasibility never silently aborts.</b> When the pre-flight dry-run cannot be
     * <em>attempted</em> — an infeasibility rather than a rejection: 401/403 (not entitled), 429
     * (throttled), 5xx (server-side), or a transport/timeout error, classified by
     * {@link PlanValidator#classifyLiveFailure(Throwable)} — the run does <em>not</em> abort. It records
     * a recoverable warning that the pre-flight could not run and proceeds to the real create, which
     * surfaces any genuine error itself. Only a true rejection aborts and rolls back. The fail-fast on a
     * missing cloud authorization key (below) is unchanged.</p>
     *
     * <p><b>Required customer inputs.</b> The cloud authorization keys — which a brand-new customer
     * gathers from each cloud console — are supplied via {@code inputs} (keyed by connection name), or
     * carried on the plan itself for a lens-3b plan. Before anything is provisioned, execution fails
     * fast if any provider connection that needs a key is missing one, naming the connection and the
     * exact key ({@link ConnectionInputRequirement}).</p>
     *
     * <p>Operational errors (a Cloud Router that does not reach {@code PROVISIONED} within the timeout,
     * a missing upstream dependency) are captured in the outcome rather than thrown, allowing a partial
     * deployment to be inspected and {@link #rollback(DeploymentOutcome) rolled back} by the caller.</p>
     *
     * <p><b>An invalid plan never executes.</b> A plan whose validation found hard errors
     * ({@code isValid() == false}) is refused up front with an {@link IllegalStateException} listing
     * every recorded error — executing it would provision billable resources and then fail
     * downstream on the very defects validation already named. Fix the errors and re-plan (or
     * {@link #dryRun()} again) before executing.</p>
     *
     * @param inputs the per-connection authorization keys, VLAN tags and Azure peering types the
     *               customer supplies; {@code null} is treated as {@link ExecutionInputs#none()}
     * @return the execution outcome with all provisioned resources and any errors
     * @throws IllegalStateException if the plan is not valid — the message lists the validation
     *         errors to fix before re-planning
     */
    public DeploymentOutcome execute(ExecutionInputs inputs) {
        if (!valid) {
            String detail = validationErrors == null || validationErrors.isEmpty()
                    ? "(no error detail was recorded on the plan)"
                    : String.join("; ", validationErrors);
            throw new IllegalStateException("This deployment plan failed validation and cannot be "
                    + "executed — executing it would provision billable resources that are known to "
                    + "fail. Fix the following and re-plan: " + detail);
        }
        ExecutionInputs in = inputs != null ? inputs : ExecutionInputs.none();
        long startTime = System.currentTimeMillis();
        List<ProvisionedResource> resources = new ArrayList<>();
        List<ProvisioningError> errors = new ArrayList<>();
        Map<String, String> routerUuids = new HashMap<>();
        Map<String, String> connectionUuids = new HashMap<>();

        // Fail fast BEFORE any billable resource is created: every provider connection that needs a
        // cloud authorization key must have one, from the plan or from the supplied inputs. A missing
        // key names the connection and the exact key a first-time customer must gather.
        List<ProvisioningError> missingInputs = missingRequiredInputs(in);
        if (!missingInputs.isEmpty()) {
            errors.addAll(missingInputs);
            return outcome(resources, false, errors, startTime);
        }

        // Phase 1: Create Cloud Routers
        if (cloudRouters != null) {
            for (PlannedCloudRouter planned : cloudRouters) {
                // The package code was resolved and validated at plan time by
                // DeploymentWizard.Builder#routerPackage. Plans built by hand can still carry a
                // null/UNKNOWN placeholder, which must never be sent to the API — record the error
                // without issuing the create rather than failing mid-deployment.
                GatewayPackageCode packageCode = planned.getPackageCode();
                if (packageCode == null || packageCode == GatewayPackageCode.UNKNOWN) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("CloudRouter")
                            .resourceName(planned.getName())
                            .reason("missing or unknown package code (" + packageCode
                                    + ") — nothing was sent to the API")
                            .recoverable(false)
                            .build());
                    continue;
                }
                try {
                    // The body comes from the SAME shared builder the plan-time Layer-2 dry-run
                    // used (RouterBodies): identical notification stamping (Fabric-mandated,
                    // EQ-3040013) and identical null guards on account/project — so a green dry-run
                    // is followed by an identical real create, not a drifted one that 400s.
                    CloudRouter cr = RouterBodies.routerBody(fabric.cloudRouters(), planned).create();

                    routerUuids.put(planned.getName(), cr.getUuid());
                    // Wait for the router to become active before the connections (and the routing
                    // protocols built on them) that depend on it are created — provisioning is async,
                    // and building a dependent against a still-provisioning router fails.
                    AwaitOutcome wait = awaitState(() -> fabric.cloudRouters().getByUuid(cr.getUuid()),
                            CloudRouter::getState, CloudRouterState.PROVISIONED,
                            Set.of(CloudRouterState.NOT_PROVISIONED, CloudRouterState.DEPROVISIONED));
                    if (wait.terminallyFailed()) {
                        // The real terminal state, not a mislabelled "PROVISIONING": dependents are
                        // skipped (the router is dropped from the uuid map) rather than doomed.
                        errors.add(ProvisioningError.builder()
                                .resourceType("CloudRouter")
                                .resourceName(planned.getName())
                                .reason("reached terminal state " + wait.statusOr("(unobserved)")
                                        + " and will never reach PROVISIONED — dependent connections skipped")
                                .recoverable(true)
                                .build());
                        routerUuids.remove(planned.getName());
                    }
                    else if (!wait.ready()) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("CloudRouter")
                                .resourceName(planned.getName())
                                .reason("did not reach PROVISIONED within the timeout")
                                .recoverable(true)
                                .build());
                    }
                    resources.add(ProvisionedResource.builder()
                            .resourceType("CloudRouter")
                            .name(planned.getName())
                            .uuid(cr.getUuid())
                            .metroId(planned.getMetroId())
                            .status(wait.statusOr("PROVISIONING"))
                            .build());
                }
                catch (Exception e) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("CloudRouter")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                }
            }
        }

        // Phase 2: Create Provider Connections — the Layer 3a pre-flight lives here. By now the A-side
        // FCR is provisioned, so its real uuid can carry a full connection body: pre-flight it with a
        // live dry-run, and create it for real only if the dry-run passes.
        if (providerConnections != null) {
            for (PlannedConnection planned : providerConnections) {
                boolean onPort = planned.getASidePortUuid() != null;
                // Resolve the real A-side endpoint: a caller-supplied pre-existing FCR (lens 3b),
                // otherwise the FCR this run just provisioned in Phase 1 (lens 3a).
                String aSideUuid = planned.getASideExistingRouterUuid() != null
                        ? planned.getASideExistingRouterUuid()
                        : routerUuids.get(planned.getASideRouterName());
                if (!onPort && aSideUuid == null) {
                    // The A-side FCR failed to provision upstream — skip the dependent connection
                    // (a missing dependency, not a validation failure), consistent with orphaned
                    // routing protocols below.
                    errors.add(ProvisioningError.builder()
                            .resourceType("Connection")
                            .resourceName(planned.getName())
                            .reason("A-side Cloud Router '" + planned.getASideRouterName()
                                    + "' was not provisioned — connection skipped")
                            .recoverable(false)
                            .build());
                    continue;
                }

                // Merge the customer inputs (auth key, VLAN, Azure peering) onto the planned connection
                // so the reused ConnectionBodies builder assembles a complete cloud VC body.
                PlannedConnection resolved = withInputs(planned, in);

                // Pre-flight: a REAL dry-run against the now-real A-side + the customer auth key. A
                // genuine REJECTION means the connection is not viable — abort and roll back everything
                // prior. An INFEASIBILITY (not entitled / throttled / server-side / transport) must NOT
                // silently abort the whole provisioning: record a skip and proceed to the real create.
                try {
                    providerBody(resolved, aSideUuid, onPort).dryRun().create();
                }
                catch (Exception e) {
                    PlanValidator.LiveFailure failure = PlanValidator.classifyLiveFailure(e);
                    if (failure.isInfeasible()) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("Connection")
                                .resourceName(planned.getName())
                                .reason("pre-flight dry-run skipped (" + failure.reason()
                                        + ") — proceeding to create, which surfaces any true error")
                                .recoverable(true)
                                .build());
                    }
                    else {
                        errors.add(ProvisioningError.builder()
                                .resourceType("Connection")
                                .resourceName(planned.getName())
                                .reason("pre-flight dry-run rejected: " + e.getMessage())
                                .recoverable(true)
                                .build());
                        return abortAndRollback(resources, errors, startTime);
                    }
                }

                // Dry-run passed (or was skipped as infeasible): create for real (a fresh builder — the
                // dry-run one is spent). A rejection would have aborted above, so reaching here is safe.
                try {
                    Connection conn = providerBody(resolved, aSideUuid, onPort).create();

                    // Real terminal-failure states, not Set.of(): a connection that lands FAILED /
                    // CANCELLED / DEPROVISIONED must stop polling immediately (no 5-minute burn), be
                    // reported with its REAL state, and have its dependent routing protocols skipped
                    // — so its uuid is only registered for Phase 4 when it did not terminally fail.
                    AwaitOutcome wait = awaitState(() -> fabric.connections().getByUuid(conn.getUuid()),
                            Connection::getState, ConnectionState.PROVISIONED, CONNECTION_TERMINAL_FAILURES);
                    if (wait.terminallyFailed()) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("Connection")
                                .resourceName(planned.getName())
                                .reason("reached terminal state " + wait.statusOr("(unobserved)")
                                        + " and will never reach PROVISIONED — routing protocols skipped")
                                .recoverable(true)
                                .build());
                    }
                    else {
                        connectionUuids.put(planned.getName(), conn.getUuid());
                        if (!wait.ready()) {
                            errors.add(ProvisioningError.builder()
                                    .resourceType("Connection")
                                    .resourceName(planned.getName())
                                    .reason("did not reach PROVISIONED within the timeout")
                                    .recoverable(true)
                                    .build());
                        }
                    }
                    resources.add(ProvisionedResource.builder()
                            .resourceType("Connection")
                            .name(planned.getName())
                            .uuid(conn.getUuid())
                            .metroId(planned.getASideMetro())
                            .status(wait.statusOr("PROVISIONING"))
                            .build());
                }
                catch (Exception e) {
                    // The dry-run passed but the real create was rejected — a hard failure; abort and
                    // roll back rather than leave a half-built, billable deployment behind.
                    errors.add(ProvisioningError.builder()
                            .resourceType("Connection")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                    return abortAndRollback(resources, errors, startTime);
                }
            }
        }

        // Phase 3: Create Backbone Links (Cloud Router → Cloud Router). Both router uuids are known
        // after Phase 1, so the same pre-flight applies: dry-run the full CR→CR body, then create.
        if (backboneLinks != null) {
            for (PlannedBackboneLink link : backboneLinks) {
                PlannedConnection planned = link.getConnection();
                String aSideUuid = routerUuids.get(planned.getASideRouterName());
                String zSideUuid = routerUuids.get(planned.getZSideRouterName());
                if (aSideUuid == null || zSideUuid == null) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("BackboneLink")
                            .resourceName(planned.getName())
                            .reason("backbone endpoints were not provisioned (A-side '"
                                    + planned.getASideRouterName() + "', Z-side '"
                                    + planned.getZSideRouterName() + "') — link skipped")
                            .recoverable(false)
                            .build());
                    continue;
                }

                // Pre-flight the backbone link the same way (both endpoints are real). A genuine
                // rejection aborts + rolls back; an infeasibility is skipped and the create proceeds.
                try {
                    ConnectionBodies.backboneBody(fabric.connections(), planned, aSideUuid, zSideUuid)
                            .dryRun().create();
                }
                catch (Exception e) {
                    PlanValidator.LiveFailure failure = PlanValidator.classifyLiveFailure(e);
                    if (failure.isInfeasible()) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("BackboneLink")
                                .resourceName(planned.getName())
                                .reason("pre-flight dry-run skipped (" + failure.reason()
                                        + ") — proceeding to create, which surfaces any true error")
                                .recoverable(true)
                                .build());
                    }
                    else {
                        errors.add(ProvisioningError.builder()
                                .resourceType("BackboneLink")
                                .resourceName(planned.getName())
                                .reason("pre-flight dry-run rejected: " + e.getMessage())
                                .recoverable(true)
                                .build());
                        return abortAndRollback(resources, errors, startTime);
                    }
                }

                try {
                    Connection conn = ConnectionBodies
                            .backboneBody(fabric.connections(), planned, aSideUuid, zSideUuid)
                            .create();

                    // Same terminal-failure handling as the provider-connection path: report the
                    // real terminal state and skip the dependent routing protocols.
                    AwaitOutcome wait = awaitState(() -> fabric.connections().getByUuid(conn.getUuid()),
                            Connection::getState, ConnectionState.PROVISIONED, CONNECTION_TERMINAL_FAILURES);
                    if (wait.terminallyFailed()) {
                        errors.add(ProvisioningError.builder()
                                .resourceType("BackboneLink")
                                .resourceName(planned.getName())
                                .reason("reached terminal state " + wait.statusOr("(unobserved)")
                                        + " and will never reach PROVISIONED — routing protocols skipped")
                                .recoverable(true)
                                .build());
                    }
                    else {
                        connectionUuids.put(planned.getName(), conn.getUuid());
                        if (!wait.ready()) {
                            errors.add(ProvisioningError.builder()
                                    .resourceType("BackboneLink")
                                    .resourceName(planned.getName())
                                    .reason("did not reach PROVISIONED within the timeout")
                                    .recoverable(true)
                                    .build());
                        }
                    }
                    resources.add(ProvisionedResource.builder()
                            .resourceType("BackboneLink")
                            .name(planned.getName())
                            .uuid(conn.getUuid())
                            .metroId(link.getMetroA())
                            .status(wait.statusOr("PROVISIONING"))
                            .build());
                }
                catch (Exception e) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("BackboneLink")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                    return abortAndRollback(resources, errors, startTime);
                }
            }
        }

        // Phase 4: Create Routing Protocols
        if (routingProtocols != null) {
            for (PlannedRoutingProtocol planned : routingProtocols) {
                String connectionUuid = connectionUuids.get(planned.getConnectionName());
                if (connectionUuid == null) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("RoutingProtocol")
                            .resourceName(planned.getName())
                            .reason("Parent connection '" + planned.getConnectionName() + "' was not provisioned")
                            .recoverable(false)
                            .build());
                    continue;
                }
                try {
                    var rpBuilder = fabric.routingProtocols().define()
                            .ofType(planned.getType())
                            .withName(planned.getName());

                    if (planned.getType() == RoutingProtocolType.BGP) {
                        rpBuilder.withCustomerAsn(planned.getCustomerAsn())
                                .withBGPIpv4(planned.getCustomerPeerIpv4(), planned.getEquinixPeerIpv4(), true)
                                .withBFD(planned.isBfdEnabled(), planned.getBfdInterval());
                    }
                    else if (planned.getType() == RoutingProtocolType.DIRECT) {
                        rpBuilder.withDirectIpv4(planned.getEquinixIfaceIpv4());
                    }

                    RoutingProtocol rp = rpBuilder.create(connectionUuid);
                    resources.add(ProvisionedResource.builder()
                            .resourceType("RoutingProtocol")
                            .name(planned.getName())
                            .uuid(rp.getUuid())
                            .status("PROVISIONED")
                            .build());
                }
                catch (Exception e) {
                    errors.add(ProvisioningError.builder()
                            .resourceType("RoutingProtocol")
                            .resourceName(planned.getName())
                            .reason(e.getMessage())
                            .recoverable(true)
                            .build());
                }
            }
        }

        return outcome(resources, errors.isEmpty(), errors, startTime);
    }

    // ══════════════════════════════════════════════
    //  Execution-time connection pre-flight helpers (Layer 3a)
    // ══════════════════════════════════════════════

    /**
     * The provider connections that cannot be provisioned because a required cloud authorization key is
     * neither carried on the plan nor supplied in {@code inputs}. A key is required for every
     * well-known cloud (AWS, Azure, GCP, ...); a third-party ({@link CloudProviderType#OTHER}) profile
     * needs none. Each returned error names the connection and the exact key to gather.
     */
    private List<ProvisioningError> missingRequiredInputs(ExecutionInputs inputs) {
        List<ProvisioningError> missing = new ArrayList<>();
        if (providerConnections == null) {
            return missing;
        }
        for (PlannedConnection conn : providerConnections) {
            CloudProviderType type = conn.getZSideCloudType() != null
                    ? conn.getZSideCloudType()
                    : ConnectionBodies.resolveCloudType(conn.getZSideProviderLabel());
            if (type == CloudProviderType.OTHER) {
                continue; // a third-party service profile needs no cloud authorization key
            }
            String key = conn.getZSideAuthenticationKey() != null
                    ? conn.getZSideAuthenticationKey()
                    : inputs.authenticationKeyFor(conn.getName());
            if (key == null || key.isBlank()) {
                missing.add(ProvisioningError.builder()
                        .resourceType("Connection")
                        .resourceName(conn.getName())
                        .reason("missing required authorization key: "
                                + ConnectionBodies.authenticationKeyLabel(type)
                                + " — supply it via ExecutionInputs before executing")
                        .recoverable(false)
                        .build());
            }
        }
        return missing;
    }

    /**
     * Returns a copy of the planned connection with the customer-supplied authorization key, VLAN tag
     * and Azure peering type merged in. A value already on the plan (a lens-3b plan) wins; otherwise
     * the value from {@code inputs} fills the field the plan deliberately left null.
     */
    private static PlannedConnection withInputs(PlannedConnection planned, ExecutionInputs inputs) {
        String key = planned.getZSideAuthenticationKey() != null
                ? planned.getZSideAuthenticationKey()
                : inputs.authenticationKeyFor(planned.getName());
        Integer vlan = planned.getZSideVlanTag() != null
                ? planned.getZSideVlanTag()
                : inputs.vlanTagFor(planned.getName());
        PeeringType peering = planned.getZSidePeeringType() != null
                ? planned.getZSidePeeringType()
                : inputs.peeringTypeFor(planned.getName());
        return planned.toBuilder()
                .zSideAuthenticationKey(key)
                .zSideVlanTag(vlan)
                .zSidePeeringType(peering)
                .build();
    }

    /**
     * Assembles a provider connection body via the shared {@link ConnectionBodies}, against a
     * pre-existing customer port (lens 3b) or the resolved A-side Cloud Router uuid. The returned
     * builder is un-terminated: chain {@code .dryRun().create()} to pre-flight or {@code .create()} to
     * provision.
     */
    private ConnectionOperator.ConnectionBuilder providerBody(
            PlannedConnection resolved, String aSideUuid, boolean onPort) {
        return onPort
                ? ConnectionBodies.providerBodyOnPort(fabric.connections(), resolved, resolved.getASidePortUuid())
                : ConnectionBodies.providerBody(fabric.connections(), resolved, aSideUuid);
    }

    /**
     * Aborts an in-flight execution and unwinds every resource provisioned so far (LIFO), reusing the
     * existing {@link #rollback(DeploymentOutcome)} machinery. Returns a not-successful outcome whose
     * errors carry the failure that triggered the abort plus any rollback-delete failures; the
     * {@code resources} list is the audit trail of what was created (and has now been torn down).
     */
    private DeploymentOutcome abortAndRollback(
            List<ProvisionedResource> resources, List<ProvisioningError> errors, long startTime) {
        DeploymentOutcome interim = outcome(resources, false, errors, startTime);
        List<ProvisioningError> rollbackFailures = rollback(interim);
        List<ProvisioningError> combined = new ArrayList<>(errors);
        combined.addAll(rollbackFailures);
        return outcome(resources, false, combined, startTime);
    }

    private DeploymentOutcome outcome(
            List<ProvisionedResource> resources, boolean success,
            List<ProvisioningError> errors, long startTime) {
        return DeploymentOutcome.builder()
                .plan(this)
                .resources(resources)
                .fullySuccessful(success)
                .errors(errors)
                .executionTimeMs(System.currentTimeMillis() - startTime)
                .build();
    }

    /**
     * The connection states that will never transition to {@code PROVISIONED}: a connection observed
     * in one of these must stop being polled immediately (no 5-minute timeout burn), be reported with
     * its REAL terminal state, and have its dependent routing protocols skipped. The old code passed
     * {@code Set.of()} here, so a FAILED connection polled to timeout and was then misreported as
     * "PROVISIONING" while Phase&nbsp;4 still attempted routing protocols on it.
     */
    private static final Set<ConnectionState> CONNECTION_TERMINAL_FAILURES = Set.of(
            ConnectionState.FAILED,
            ConnectionState.CANCELLED,
            ConnectionState.DEPROVISIONED,
            ConnectionState.DEPROVISIONING);

    /**
     * The outcome of one state wait: whether the resource became {@code ready}, and the state it was
     * last observed in — the ready state, the REAL terminal-failure state, or {@code null} when the
     * wait timed out / the fetch itself failed (no state was observed at all).
     */
    private record AwaitOutcome(boolean ready, boolean terminallyFailed, String status) {

        /** The observed state name, or {@code fallback} when no state could be observed. */
        String statusOr(String fallback) {
            return status != null ? status : fallback;
        }
    }

    /**
     * Polls the given resource until it reaches {@code ready}, hits one of {@code terminalFailures},
     * or the timeout (5 minutes, polled every 5 seconds) elapses. The returned {@link AwaitOutcome}
     * distinguishes ready / terminally-failed (with the real terminal state) / timed-out — letting
     * {@link #execute()} record a recoverable error with the actual observed status rather than
     * asserting a state that never held.
     */
    private static <T, S extends Enum<S>> AwaitOutcome awaitState(Supplier<T> fetch, Function<T, S> state,
                                                                  S ready, Set<S> terminalFailures) {
        try {
            T resource = ResourceWaiter.forResource(fetch)
                    .until(r -> state.apply(r) == ready)
                    .failWhen(r -> terminalFailures.contains(state.apply(r)))
                    .timeout(Duration.ofMinutes(5))
                    .pollInterval(Duration.ofSeconds(5))
                    .await();
            return new AwaitOutcome(true, false, state.apply(resource).name());
        }
        catch (WaiterFailedException e) {
            // The resource reached a terminal failure state — surface the REAL state it landed in.
            String observed = null;
            try {
                @SuppressWarnings("unchecked")
                T failedResource = (T) e.getResource();
                if (failedResource != null) {
                    observed = state.apply(failedResource).name();
                }
            }
            catch (RuntimeException ignored) {
                // A cast/accessor problem must not mask the terminal-failure verdict itself.
            }
            return new AwaitOutcome(false, true, observed);
        }
        catch (RuntimeException e) {
            // WaiterTimeoutException (or a fetch error) — not ready, and no terminal state observed.
            return new AwaitOutcome(false, false, null);
        }
    }

    /**
     * Best-effort teardown of the resources provisioned by a prior {@link #execute()}: deletes the
     * connections (and backbone links), then the Cloud Routers, in reverse dependency order. Routing
     * protocols are removed with their parent connection. Use this to clean up a partially-failed
     * deployment rather than leaving orphaned, billable resources behind.
     *
     * @param outcome the outcome returned by {@link #execute()}
     * @return the deletions that failed (empty when the rollback was clean)
     */
    public List<ProvisioningError> rollback(DeploymentOutcome outcome) {
        List<ProvisioningError> failures = new ArrayList<>();
        if (outcome == null || outcome.getResources() == null) {
            return failures;
        }
        List<ProvisionedResource> reversed = new ArrayList<>(outcome.getResources());
        Collections.reverse(reversed);
        for (ProvisionedResource resource : reversed) {
            if (resource.getUuid() == null) {
                continue;
            }
            try {
                switch (resource.getResourceType()) {
                    case "Connection":
                    case "BackboneLink":
                        fabric.connections().getByUuid(resource.getUuid()).delete();
                        break;
                    case "CloudRouter":
                        fabric.cloudRouters().getByUuid(resource.getUuid()).delete();
                        break;
                    default:
                        // RoutingProtocol and any others are removed with their parent connection.
                        break;
                }
            }
            catch (RuntimeException e) {
                failures.add(ProvisioningError.builder()
                        .resourceType(resource.getResourceType())
                        .resourceName(resource.getName())
                        .reason("rollback delete failed: " + e.getMessage())
                        .recoverable(false)
                        .build());
            }
        }
        return failures;
    }
}
