/*
 * Copyright 2021 Ian Jones. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package api.equinix.javasdk.ibxsmartview.client;

import api.equinix.javasdk.core.http.response.PaginatedList;
import api.equinix.javasdk.ibxsmartview.model.SystemAlert;

/**
 * Client interface for querying IBX SmartView system alerts. Provides methods to search
 * for alerts generated by monitored assets in Equinix data centers using either query
 * parameters or a structured filter body.
 */
public interface SystemAlerts {

    /**
     * Searches for system alerts matching the specified filter criteria.
     *
     * @param status the alert status to filter by
     * @param assetClassification the asset classification to filter by
     * @param edgeCollectedOn the edge collection date to filter by
     * @param offset the zero-based offset for pagination
     * @param limit the maximum number of results to return
     * @return a paginated list of matching system alerts
     */
    PaginatedList<SystemAlert> search(String status, String assetClassification, String edgeCollectedOn, int offset, int limit);

    /**
     * Searches for system alerts using a structured filter body submitted via POST.
     *
     * @param filterBody the filter criteria as a request body object
     * @return a paginated list of matching system alerts
     */
    PaginatedList<SystemAlert> searchPost(Object filterBody);
}
