/*
 * Copyright 2021 Ian Jones. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package api.equinix.javasdk;

import api.equinix.javasdk.core.auth.EquinixCredentials;
import api.equinix.javasdk.core.model.Service;
import api.equinix.javasdk.messaging.client.Events;
import api.equinix.javasdk.messaging.client.MessagingConfig;
import api.equinix.javasdk.messaging.client.Subscriptions;
import api.equinix.javasdk.messaging.client.implementation.EventsImpl;
import api.equinix.javasdk.messaging.client.implementation.MessagingConfigImpl;
import api.equinix.javasdk.messaging.client.implementation.SubscriptionsImpl;

/**
 * The primary entry point for accessing Equinix Messaging APIs.
 *
 * <p>Messaging provides notification and event management capabilities for Equinix
 * platform resources. This class offers typed access to notification subscriptions
 * and event streams that enable automated workflows and monitoring.</p>
 *
 * <p>All resource accessors use lazy initialization — internal clients are created on first access
 * and reused for subsequent calls.</p>
 *
 * <h3>Quick Start</h3>
 * <pre>{@code
 * BasicEquinixCredentials credentials = new BasicEquinixCredentials("clientId", "clientSecret");
 * Messaging messaging = new Messaging(credentials);
 *
 * // List notification subscriptions
 * PaginatedList<Subscription> subs = messaging.subscriptions().list();
 *
 * // List events
 * PaginatedList<Event> events = messaging.events().list();
 * }</pre>
 *
 * @author ianjones
 * @see api.equinix.javasdk.core.auth.BasicEquinixCredentials
 */
public final class Messaging extends EquinixClient implements Service {

    private Subscriptions subscriptions;

    private Events events;

    final private MessagingConfig messagingConfig;

    /**
     * Creates a new Messaging client using the provided credentials.
     * Authentication occurs automatically on the first API call.
     *
     * @param equinixCredentials the OAuth2 credentials for authenticating with Equinix APIs
     */
    public Messaging(EquinixCredentials equinixCredentials) {
        this(equinixCredentials, false);
    }

    /**
     * Creates a new Messaging client with optional sandbox mode.
     *
     * @param equinixCredentials the OAuth2 credentials for authenticating with Equinix APIs
     * @param isSandBoxed {@code true} to use the sandbox environment for testing; {@code false} for production
     */
    public Messaging(EquinixCredentials equinixCredentials, boolean isSandBoxed) {
        super(equinixCredentials, isSandBoxed);

        String paramFile = "json/apiParams_Messaging.json";
        equinixClient.appendApiParams(paramFile);

        this.messagingConfig = new MessagingConfigImpl(equinixClient);
    }

    /**
     * Returns the client for managing notification subscriptions.
     * Subscriptions define which events trigger notifications and how they are delivered.
     *
     * @return the {@link Subscriptions} client for creating and managing notification subscriptions
     */
    public Subscriptions subscriptions() {
        if (this.subscriptions == null) {
            this.subscriptions = new SubscriptionsImpl(this.messagingConfig.getSubscriptionClient(), this);
        }
        return subscriptions;
    }

    /**
     * Returns the client for accessing messaging events.
     * Events represent notifications and messages generated by Equinix platform operations.
     *
     * @return the {@link Events} client for listing and querying messaging events
     */
    public Events events() {
        if (this.events == null) {
            this.events = new EventsImpl(this.messagingConfig.getEventClient(), this);
        }
        return events;
    }
}
